### ISSUE TITLE
Will not run Color Picker after installation. 

### ISSUE THREAD

**Issue by silocoder** [anseki/vscode-color#102]
```
- Extension Version: 0.4.5
- VS Code Version:
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-45-generic


- OS Version:5.4.0-45-generic #49-Ubuntu
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):
~$ node -v
v12.18.3
~$ npm -v
6.14.6

```

Press Alt C + P
Tries to install then crashes

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Start child process...
console.ts:137 [Extension Host] Check version of: electron-prebuilt
console.ts:137 [Extension Host] Check version of: comma-separated-values
console.ts:137 [Extension Host] Check version of: js-yaml
console.ts:137 [Extension Host] Check version of: process-bridge
console.ts:137 [Extension Host] Try to send IPC message: 1
console.ts:137 [Extension Host] [STDERR]: /home/silocoder/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
console.ts:137 [Extension Host] Child process disconnected
console.ts:137 [Extension Host] Child process exited with code: 127
console.ts:137 [Extension Host] Error: Child process exited with code: 127
	at /home/silocoder/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19
	at ChildProcess.<anonymous> (/home/silocoder/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at ChildProcess.emit (events.js:203:13)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
notificationsAlerts.ts:40 [processBridge]: Error: Child process exited with code: 127
console.ts:137 [Extension Host] Error: Child process already exited.
	at sendIpc (/home/silocoder/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)
	at Timeout.<anonymous> (/home/silocoder/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
notificationsAlerts.ts:40 [processBridge]: Error: Child process already exited.
﻿
```
![image](https://user-images.githubusercontent.com/57298274/92316368-ebf9d700-efc0-11ea-979d-b2e31aa15d11.png)

**Comment by anseki** [comment]
Hi @silocoder, thank you for the comment.
This may help you: https://github.com/anseki/vscode-color/issues/95

**Comment by silocoder** [comment]
Unfortunately there are now other issues so I installed this because it was saying its missing it:
`sudo apt-get install appmenu-gtk2-module appmenu-gtk3-module`

Now it is saying this and I am not sure what the Pango and Harfbuzz steps are to update:
```
[Extension Host] Start child process...
console.ts:137 [Extension Host] Check version of: electron-prebuilt
console.ts:137 [Extension Host] Check version of: comma-separated-values
console.ts:137 [Extension Host] Check version of: js-yaml
console.ts:137 [Extension Host] Check version of: process-bridge
console.ts:137 [Extension Host] Try to send IPC message: 1
console.ts:137 [Extension Host] [STDERR]: (electron:5955): Pango-ERROR **: 23:46:21.341: Harfbuzz version too old (1.1.3)

```

**Comment by anseki** [comment]
The issue might be solved by downgrading the glibc in your computer, but I don't know whether this is best solution or not.
Sorry, I can't help you about this.
I think that you had better use internal Color Picker of VS Code instead.

**Comment by silocoder** [comment]
Ok thanks.

**Comment by anseki** [comment]
:smile: 
Could you close this issue if it was solved?

**Comment by silocoder** [comment]
Closed!
