### ISSUE TITLE
Harfbuzz version too old (1.1.3)

### ISSUE THREAD

**Issue by ferretwithaberet** [anseki/vscode-color#105]
- Extension Version: 0.4.5
- VS Code Version: 1.51.1
- OS Version:  Linux x64 5.4.74-1-MANJARO
- Node.js Version (result of command `node -v`): v14.15.0 (Installed through `nvm`)
- NPM Version (result of command `npm -v`): 6.14.8

Steps to Reproduce:

1. Install extension while having an updated version of `pango` library.
2. Try to use it.

Possible solution:
While searching for this error, I saw that a lot of people say that updating the electron used for the package fixed this. This extension is also using `electron-prebuilt` which is marked as deprecated and it was renamed to `electron`. I also saw that you were pointing people into downgrading `glibc`(even though you were saying "I don't know whether this is best solution or not") which is not a great solution in my opinion. This extension needs to be updated as it uses packages that have severe vulnerabilities.

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Start child process...
console.ts:137 [Extension Host] Check version of: electron-prebuilt
console.ts:137 [Extension Host] Check version of: comma-separated-values
console.ts:137 [Extension Host] Check version of: js-yaml
console.ts:137 [Extension Host] Check version of: process-bridge
console.ts:137 [Extension Host] Try to send IPC message: 1
console.ts:137 [Extension Host] Try to send IPC message: 2
console.ts:137 [Extension Host] Try to send IPC message: 3
console.ts:137 [Extension Host] Try to send IPC message: 4
console.ts:137 [Extension Host] [STDERR]: (electron:66660): Pango-ERROR **: 23:43:13.985: Harfbuzz version too old (1.1.3)
t.log @ console.ts:140
$logExtensionHostMessage @ mainThreadConsole.ts:29
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:431
_receiveMessage @ ipc.net.ts:764
(anonymous) @ ipc.net.ts:624
fire @ event.ts:584
acceptChunk @ ipc.net.ts:174
(anonymous) @ ipc.net.ts:174
t @ ipc.net.ts:900
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] Child process disconnected
console.ts:137 [Extension Host] Child process exited with code: null
console.ts:137 [Extension Host] Error: Child process exited with code: null    at /home/ferretwithaberet/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19    at ChildProcess.<anonymous> (/home/ferretwithaberet/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)    at ChildProcess.emit (events.js:223:5)    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
t.log @ console.ts:140
$logExtensionHostMessage @ mainThreadConsole.ts:29
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:431
_receiveMessage @ ipc.net.ts:764
(anonymous) @ ipc.net.ts:624
fire @ event.ts:584
acceptChunk @ ipc.net.ts:174
(anonymous) @ ipc.net.ts:174
t @ ipc.net.ts:900
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
notificationsAlerts.ts:40 [processBridge]: Error: Child process exited with code: null
onDidChangeNotification @ breadcrumbsModel.ts:39
(anonymous) @ breadcrumbsModel.ts:39
fire @ event.ts:584
addNotification @ notifications.ts:204
notify @ notificationService.ts:88
(anonymous) @ mainThreadLogService.ts:16
_showMessage @ mainThreadLogService.ts:16
$showMessage @ mainThreadLogService.ts:16
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:431
_receiveMessage @ ipc.net.ts:764
(anonymous) @ ipc.net.ts:624
fire @ event.ts:584
acceptChunk @ ipc.net.ts:174
(anonymous) @ ipc.net.ts:174
t @ ipc.net.ts:900
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] Error: Child process already exited.    at sendIpc (/home/ferretwithaberet/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)    at Timeout.<anonymous> (/home/ferretwithaberet/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)    at listOnTimeout (internal/timers.js:531:17)    at processTimers (internal/timers.js:475:7)
t.log @ console.ts:140
$logExtensionHostMessage @ mainThreadConsole.ts:29
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:431
_receiveMessage @ ipc.net.ts:764
(anonymous) @ ipc.net.ts:624
fire @ event.ts:584
acceptChunk @ ipc.net.ts:174
(anonymous) @ ipc.net.ts:174
t @ ipc.net.ts:900
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
notificationsAlerts.ts:40 [processBridge]: Error: Child process already exited.
```

**Comment by anseki** [comment]
Hi @ferretwithaberet, thank you for the comment.
I think that this extension has already finished its part since VS Code supports internal Color Picker.
I recommend using internal Color Picker instead.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
