### ISSUE TITLE
Extension not working on WSL.

### ISSUE THREAD

**Issue by IlanVivanco** [anseki/vscode-color#107]
I'm getting this error on WSL side

![image](https://user-images.githubusercontent.com/9307840/105898185-e8123400-5ff7-11eb-9ef7-05c37c00dd48.png)

On Windows side, it's not working either, but not showing any error. It just auto select the color but no picker is prompted.

- Extension Version: 0.4.5
- VS Code Version: 1.52.1
- OS Version: Windows 10 Pro
- Node.js Version (result of command `node -v`): 14.6.0
- NPM Version (result of command `npm -v`): 6.14.6

Steps to Reproduce:

1. Install extension on WSL
2. select a color and trigger color picker (ALT + C / P)

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)

```
Extension Host
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5009 [0126/204917.473:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
7/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5432 [MehediDracula.php-namespace-resolver]: Menu item references the same command as default and alt-command
12/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5432 [Hridoy.jquery-snippets]: Unknown language in `contributes.jquery-snippets.language`. Provided value: 'javascript'
_logMessageInConsole @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5432
workbench.html:1 A cookie associated with a cross-site resource at https://visualstudio.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5519 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Users/melio/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu-20.04/home/ilan/.vscode-server/extensions/redhat.vscode-yaml-0.14.0/syntaxes/yaml.tmLanguage.json
register @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5519
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] (node:9169) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Looking for parseable documents...
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1779   ERR [MobX] minified error nr: 35. Find the full error at: https://github.com/mobxjs/mobx/blob/mobx6/src/errors.ts: Error: [MobX] minified error nr: 35. Find the full error at: https://github.com/mobxjs/mobx/blob/mobx6/src/errors.ts
    at r (c:\Users\melio\.vscode\extensions\codespaces-contrib.codeswing-0.0.8\dist\extension.js:2:1014430)
    at Timeout._onTimeout (c:\Users\melio\.vscode\extensions\codespaces-contrib.codeswing-0.0.8\dist\extension.js:2:1031908)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded

/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] PHP process connected
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] swdc-vscode: Loaded softwaredotcom.swdc-vscode v2.4.3
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Found all parseable documents.
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Parsing documents and looking for CSS class definitions...
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] swdc-tracker initialized and ready to send events to com-software-prod1.collector.snplow.net
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Summary:
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host]% 186 parseable documents found
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host]% 56907 CSS class definitions found
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host]% 4482 unique CSS class definitions found
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host]% 14 failed attempts to parse. List of the documents:
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] /home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/ShorthandSizeUnitTest.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/MissingColonUnitTest.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/SemicolonSpacingUnitTest.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/ColonSpacingUnitTest.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/ClassDefinitionNameSpacingUnitTest.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/ClassDefinitionOpeningBraceSpaceUnitTest.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/IndentationUnitTest.1.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/DisallowMultipleStyleDefinitionsUnitTest.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/IndentationUnitTest.2.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Squiz/Tests/CSS/DuplicateStyleDefinitionUnitTest.css/home/ilan/code/wp-boston/node_modules/combine-source-map/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css/home/ilan/code/wp-boston/css/style.min.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.2.css/home/ilan/code/wp-boston/vendor/squizlabs/php_codesniffer/src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.1.css
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Start child process...
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Check version of: electron-prebuilt
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Check version of: comma-separated-values
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Check version of: js-yaml
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Check version of: process-bridge
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Try to send IPC message: 1
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Error: write EPIPE    at ChildProcess.target._send (internal/child_process.js:806:20)    at ChildProcess.target.send (internal/child_process.js:676:19)    at /home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:418:19    at Array.forEach (<anonymous>)    at sendIpc (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:416:18)    at sendMessage (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:430:7)    at /home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:529:51    at Array.forEach (<anonymous>)    at /home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:529:23    at /home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19    at getHostCmd (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:365:5)    at /home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19    at Object.exports.sendRequest (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)    at pickConvert (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)    at exports.pick (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)    at _executeContributedCommand (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:725:220)    at _.$executeContributedCommand (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:725:595)    at m._doInvokeHandler (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:916:926)    at m._invokeHandler (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:916:618)    at m._receiveRequest (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:915:252)    at m._receiveOneMessage (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:914:6)    at /home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:912:136    at l.fire (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)    at v.fire (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:233:787)    at /home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1118:104    at l.fire (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)    at v.fire (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:233:787)    at t.PersistentProtocol._receiveMessage (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:238:1004)    at /home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:235:927    at l.fire (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)    at p.acceptChunk (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:231:195)    at /home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:230:547    at Socket.t (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:240:822)    at Socket.emit (events.js:223:5)    at addChunk (_stream_readable.js:309:12)    at readableAddChunk (_stream_readable.js:290:11)    at Socket.Readable.push (_stream_readable.js:224:10)    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
t.log @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3183 [processBridge]: Error: write EPIPE
onDidChangeNotification @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3183
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] [STDERR]: /home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
t.log @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Child process disconnected
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Child process exited with code: 127
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Error: Child process exited with code: 127    at /home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19    at ChildProcess.<anonymous> (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)    at ChildProcess.emit (events.js:223:5)    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
t.log @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3183 [processBridge]: Error: Child process exited with code: 127
onDidChangeNotification @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3183
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Error: Unexpected SIGPIPE    at process.<anonymous> (/home/ilan/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/bootstrap.js:5:614)    at process.emit (events.js:223:5)
t.log @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310 [Extension Host] Error: Child process already exited.    at sendIpc (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)    at Timeout.<anonymous> (/home/ilan/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)    at listOnTimeout (internal/timers.js:531:17)    at processTimers (internal/timers.js:475:7)
t.log @ /C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:310
/C:/Users/melio/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3183
```

**Comment by anseki** [comment]
Hi @IlanVivanco, thank you for the comment.
The error message says that a required library is not found.
Then, the issue might be solved by installing the library.
```
sudo apt install libgtk2.0-dev
```
However, the library is old, and that might not be able to be installed into your environment.
I recommend using internal Color Picker instead because VS Code already implements it.

**Comment by IlanVivanco** [comment]
Hey, thanks for the reply.

I tried to install the dependency, bur had some errors fetching some libraries.
I'll rely on the VScode option, but I needed something to convert between HSL and Hex values all at once.

In case it's useful for anybody else, I ended up using https://marketplace.visualstudio.com/items?itemName=bbugh.change-color-format

**Comment by anseki** [comment]
Thank you for the information.
So, could you close this issue?

**Comment by IlanVivanco** [comment]
Well, technically, it's not solved. I just happened to not use it after all. But feel free to close it if you want.

**Comment by anseki** [comment]
Ok.
We can do nothing for this issue. Then it is closed.
