### ISSUE TITLE
[processBridge]: TypeError: must call as: npm.load(callback)

### ISSUE THREAD

**Issue by MikkoPulkkinen** [anseki/vscode-color#108]
- Extension Version: 0.4.5
- VS Code Version: 1.53.0
- OS Version: Win 10 (Build 19041.746)
- Node.js Version (result of command `node -v`): v14.15.4
- NPM Version (result of command `npm -v`): 7.5.2

Steps to Reproduce:

1. Press alt-c p
2. Instead of opening color picker, gives error "[processBridge]: TypeError: must call as: npm.load(callback)".

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Start child process...
console.ts:137 [Extension Host] c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:215:initModule: Start initializing module...
b @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:623
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:623
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] Node.js@12.18.3
console.ts:137 [Extension Host] c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:142:getNpm: Error: Cannot find module 'npm'
Require stack:
- c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js
- c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js
- c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\extension.js
- c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1019:15)
	at Module._load (internal/modules/cjs/loader.js:895:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:27152)
	at Function.p._load (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:23904)
	at Function.M._load (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:62159)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:3:12287)
	at getNpm (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:139:15)
	at initModule (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)
	at getHostCmd (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
	at c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at Object.exports.sendRequest (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at b._executeContributedCommand (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88517)
	at b.$executeContributedCommand (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88849)
	at p._doInvokeHandler (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:10276)
	at p._invokeHandler (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9968)
	at p._receiveRequest (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8638)
	at p._receiveOneMessage (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:7440)
	at c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:5568
	at v.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:29104
	at v.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at t._receiveMessage (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:20765)
	at c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:17659
	at v.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at u.acceptChunk (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12880)
	at c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12228
	at Socket.m (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
console.ts:137 [Extension Host] c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:143:getNpm: Continue trying to get NPM...
b @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:623
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:623
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:149:getNpm: Try to get NPM via usage info.
b @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:623
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:623
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] NPM@7.5.2
console.ts:137 [Extension Host] NPM directory path: C:\Users\mikko\AppData\Roaming\npm\node_modules\npm
console.ts:137 [Extension Host] NPM resolved path: C:\Users\mikko\AppData\Roaming\npm\node_modules\npm\lib\npm.js
console.ts:137 [Extension Host] Base directory path: c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5
console.ts:137 [Extension Host] c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:206:null: TypeError: must call as: npm.load(callback)
	at Object.load (C:\Users\mikko\AppData\Roaming\npm\node_modules\npm\lib\npm.js:130:13)
	at initModule (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:233:9)
	at getHostCmd (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
	at c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at Object.exports.sendRequest (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (c:\Users\mikko\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at b._executeContributedCommand (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88517)
	at b.$executeContributedCommand (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88849)
	at p._doInvokeHandler (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:10276)
	at p._invokeHandler (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9968)
	at p._receiveRequest (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8638)
	at p._receiveOneMessage (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:7440)
	at c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:5568
	at v.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:29104
	at v.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at t._receiveMessage (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:20765)
	at c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:17659
	at v.fire (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at u.acceptChunk (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12880)
	at c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12228
	at Socket.m (c:\Users\mikko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
b @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:623
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:623
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
notificationsAlerts.ts:40 [processBridge]: TypeError: must call as: npm.load(callback)
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:623
addNotification @ notifications.ts:207
notify @ notificationService.ts:103
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:623
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:623
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
```

**Comment by anseki** [comment]
Hi @MikkoPulkkinen, thank you for the comment.
That seems a bug of NPM. (https://github.com/npm/cli/issues/2137)
Try this, then it may be solved:
**Windows**
```
cd /d %USERPROFILE%\.vscode\extensions\anseki.vscode-color-0.4.5
npm install npm@6.14.11
```
**Others**
```
cd ~/.vscode/extensions/anseki.vscode-color-0.4.5
npm install npm@6.14.11
```

**Comment by MikkoPulkkinen** [comment]
Thanks, after doing that there's no error anymore. However, the color picker still doesn't show up. Log:

console.ts:137 [Extension Host] Start child process...
console.ts:137 [Extension Host] Check version of: electron-prebuilt
console.ts:137 [Extension Host] Check version of: comma-separated-values
console.ts:137 [Extension Host] Check version of: js-yaml
console.ts:137 [Extension Host] Check version of: npm
console.ts:137 [Extension Host] Check version of: process-bridge
console.ts:137 [Extension Host] Try to send IPC message: 1

*** it waits here until mouseclick ***

console.ts:137 [Extension Host] Try to send IPC message: 2
console.ts:137 [Extension Host] Child process disconnected
console.ts:137 [Extension Host] Child process exited with code: 0

**Comment by MikkoPulkkinen** [comment]
Oh, there was already an issue about that. "colorHelper.disableGpu": 1 fixed it. Thank you!

**Comment by anseki** [comment]
:smile:

**Comment by renet** [comment]
I do get the same error! Using npm 7.6.0 on Win10 WSL2 - might there be a compatibility issue with npm7 or could it be Windows (WSL) related?

`"colorHelper.disableGpu": 1` didn't help and downgrading to npm6 isn't an option for me, either.

**Comment by anseki** [comment]
Hi @renet, thank you for the comment.
Do you mean that the solution (https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209) failed?

**Comment by renet** [comment]
I guess I didn't fully read the solution. I just scanned over it and thought your solution was to globally downgrade npm to that particular version. But you suggested to only install it inside your extension's folder.

1. I will try this.
2. This should not be the final solution. Wouldn't it be better to update your code to restore compatibility to the latest npm versions?

 Thank you!

**Comment by anseki** [comment]
Of course this is not a solution to the root of the problem.
As I said (https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209), the cause of this issue is the bug of NPM.
The bug of NPM might be fixed, or I might replace to libnpm, but I think that this extension have already finished its part since VS Code supports internal Color Picker.
