### ISSUE TITLE
with sveltekit and WindiCSS, colors in file windi.config.cjs is not working

### ISSUE THREAD

**Issue by moisesbites** [anseki/vscode-color#112]
- Extension Version: v0.4.5
- VS Code Version: 1.55.2
- OS Version: Linux Mint 20.1
- Node.js Version (result of command `node -v`): v14.16.1
- NPM Version (result of command `npm -v`): 7.10.0

Steps to Reproduce:

1. When I edit the file `windi.config.cjs` the colors is not showing the little decorator:

Example:
![image](https://user-images.githubusercontent.com/8934577/115124549-d1dd9980-9f90-11eb-9d2a-6d03503499d8.png)

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
console.ts:137 [Extension Host] Error: Cannot find module 'npm'Require stack:- /home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js- /home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js- /home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/extension.js- /usr/share/code/resources/app/out/vs/loader.js- /usr/share/code/resources/app/out/bootstrap-amd.js- /usr/share/code/resources/app/out/bootstrap-fork.js    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1019:15)    at Module._load (internal/modules/cjs/loader.js:895:27)    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)    at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:27791)    at Function.E._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:24509)    at Function.a._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:59194)    at Module.require (internal/modules/cjs/loader.js:1079:19)    at v (/usr/share/code/resources/app/out/vs/loader.js:4:694)    at getNpm (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:139:15)    at initModule (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:220:10)    at getHostCmd (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:331:9)    at /home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19    at Object.exports.sendRequest (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)    at pickConvert (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)    at exports.pick (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)    at S._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)    at S.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:107208)    at u._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)    at u._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)    at u._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)    at u._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032    at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)    at E.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:29750    at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)    at E.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)    at t._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640    at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)    at acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209    at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)    at Socket.emit (events.js:315:20)    at addChunk (_stream_readable.js:295:12)    at readableAddChunk (_stream_readable.js:271:9)    at Socket.Readable.push (_stream_readable.js:212:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
console.ts:137 [Extension Host] Continue trying to get NPM...
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] Try to get NPM via usage info.
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] NPM@7.10.0
console.ts:137 [Extension Host] NPM directory path: /home/bites/.nvm/versions/node/v14.16.1/lib/node_modules/npm
console.ts:137 [Extension Host] NPM resolved path: /home/bites/.nvm/versions/node/v14.16.1/lib/node_modules/npm/lib/npm.js
console.ts:137 [Extension Host] Base directory path: /home/bites/.vscode/extensions/anseki.vscode-color-0.4.5
console.ts:137 [Extension Host] TypeError: must call as: npm.load(callback)    at Object.load (/home/bites/.nvm/versions/node/v14.16.1/lib/node_modules/npm/lib/npm.js:127:13)    at initModule (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:233:9)    at getHostCmd (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:331:9)    at /home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19    at Object.exports.sendRequest (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)    at pickConvert (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)    at exports.pick (/home/bites/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)    at S._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)    at S.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:107208)    at u._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)    at u._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)    at u._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)    at u._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032    at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)    at E.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:29750    at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)    at E.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)    at t._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640    at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)    at acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209    at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)    at Socket.emit (events.js:315:20)    at addChunk (_stream_readable.js:295:12)    at readableAddChunk (_stream_readable.js:271:9)    at Socket.Readable.push (_stream_readable.js:212:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
notificationsAlerts.ts:40 [processBridge]: TypeError: must call as: 
```

**Comment by anseki** [comment]
Hi @moisesbites, thank you for the comment.
Try this: https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
