### ISSUE TITLE
Installing and running command throws error

### ISSUE THREAD

**Issue by nopeless** [anseki/vscode-color#117]
- Extension Version: 0.4.5
- VS Code Version: 1.59.1 x64
- OS Version: windows build 19043
- Node.js Version (result of command `node -v`): 14.10.1 with nvm for windows
- NPM Version (result of command `npm -v`): 7.20.6

Steps to Reproduce:

1. I'm not sure either. I just installed it and throws this error. I tried restarting vscode as well

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] TypeError: callback must be a function if provided    at Object.load (C:\Users\nOPE\AppData\Roaming\npm\node_modules\npm\lib\npm.js:163:13)    at initModule (c:\Users\nOPE\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:233:9)    at getHostCmd (c:\Users\nOPE\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)    at c:\Users\nOPE\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19    at Object.exports.sendRequest (c:\Users\nOPE\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)    at pickConvert (c:\Users\nOPE\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)    at exports.pick (c:\Users\nOPE\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)    at _executeContributedCommand (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:109251)    at _.$executeContributedCommand (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:109689)    at h._doInvokeHandler (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)    at h._invokeHandler (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)    at h._receiveRequest (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11159)    at h._receiveOneMessage (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)    at c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039    at d.fire (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)    at c.fire (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)    at c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060    at d.fire (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)    at c.fire (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)    at r._receiveMessage (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)    at c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969    at d.fire (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)    at v.acceptChunk (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)    at c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534    at Socket.w (c:\Users\nOPE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)    at Socket.emit (events.js:315:20)    at Socket.EventEmitter.emit (domain.js:467:12)    at addChunk (internal/streams/readable.js:309:12)    at readableAddChunk (internal/streams/readable.js:284:9)    at Socket.Readable.push (internal/streams/readable.js:223:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
S @ workbench.desktop.main.js:62
```

**Comment by anseki** [comment]
Hi @nopeless, thank you for the comment.
Try this: https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209

**Comment by nopeless** [comment]
that fixed it btw

**Comment by anseki** [comment]
:smile:
