### ISSUE TITLE
issue with M1 Mac not able to install electron

### ISSUE THREAD

**Issue by abhisheksahdev** [anseki/vscode-color#124]
- Extension Version: v0.4.5
- VS Code Version: 1.64.2 (Universal)
- OS Version: MacOS Monterey 12.2.1 (21D62) 
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):

Steps to Reproduce:

1. `cd ~/.vscode/extensions/anseki.vscode-color-0.4.5`
1. `npm i npm` 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
 INFO IExtensionHostStarter.start() took 38 ms.
workbench.desktop.main.js:578   ERR [Extension Host] (node:91748) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:75 [Extension Host] (node:91748) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Electron --trace-deprecation ...` to show where the warning was created)
I @ workbench.desktop.main.js:75
workbench.desktop.main.js:3036 [redhat.vscode-xml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:3036
workbench.desktop.main.js:3036 [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:3036
workbench.desktop.main.js:578   ERR Problems processing product icons definitions in file:///Users/abhishek/.vscode/extensions/rubenverg.bootstrap-product-icons-1.0.2/icons/bootstrap-product-icon-theme.json:
Invalid font weight in font 'bi'. Ignoring setting.
Invalid font style in font 'bi'. Ignoring setting.
Invalid font weight in font 'fira'. Ignoring setting.
Invalid font style in font 'fira'. Ignoring setting.
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope source.graphql.
Old grammar file: file:///Users/abhishek/.vscode/extensions/graphql.vscode-graphql-0.3.41/grammars/graphql.json.
New grammar file: file:///Users/abhishek/.vscode/extensions/kumar-harsh.graphql-for-vscode-1.15.3/syntaxes/graphql.json
register @ workbench.desktop.main.js:1722
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope inline.graphql.
Old grammar file: file:///Users/abhishek/.vscode/extensions/graphql.vscode-graphql-0.3.41/grammars/graphql.js.json.
New grammar file: file:///Users/abhishek/.vscode/extensions/kumar-harsh.graphql-for-vscode-1.15.3/syntaxes/graphql.js.json
register @ workbench.desktop.main.js:1722
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope markdown.graphql.codeblock.
Old grammar file: file:///Users/abhishek/.vscode/extensions/graphql.vscode-graphql-0.3.41/grammars/graphql.markdown.codeblock.json.
New grammar file: file:///Users/abhishek/.vscode/extensions/kumar-harsh.graphql-for-vscode-1.15.3/syntaxes/graphql.markdown.codeblock.json
register @ workbench.desktop.main.js:1722
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope inline.graphql.re.
Old grammar file: file:///Users/abhishek/.vscode/extensions/graphql.vscode-graphql-0.3.41/grammars/graphql.re.json.
New grammar file: file:///Users/abhishek/.vscode/extensions/kumar-harsh.graphql-for-vscode-1.15.3/syntaxes/graphql.re.json
register @ workbench.desktop.main.js:1722
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///Users/abhishek/.vscode/extensions/naco-siren.gradle-language-0.2.3/syntaxes/groovy.tmLanguage.json
register @ workbench.desktop.main.js:1722
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/abhishek/.vscode/extensions/redhat.vscode-yaml-1.4.0/syntaxes/yaml.tmLanguage.json
register @ workbench.desktop.main.js:1722
workbench.desktop.main.js:75 [Extension Host] vscode
workbench.desktop.main.js:75 [Extension Host] [Guides] Sending usage statistics...
workbench.desktop.main.js:75 [Extension Host] Looking for parseable documents...
workbench.desktop.main.js:75 [Extension Host] Found all parseable documents.
workbench.desktop.main.js:75 [Extension Host] Parsing documents and looking for CSS class definitions...
workbench.desktop.main.js:75 [Extension Host] Summary:
workbench.desktop.main.js:75 [Extension Host]% 164 parseable documents found
workbench.desktop.main.js:75 [Extension Host]% 58829 CSS class definitions found
workbench.desktop.main.js:75 [Extension Host]% 1251 unique CSS class definitions found
workbench.desktop.main.js:75 [Extension Host]% 1 failed attempts to parse. List of the documents:
workbench.desktop.main.js:75 [Extension Host] /Users/abhishek/dev/personal/Aushadhalay/AushNative/node_modules/errorhandler/public/error.html
workbench.desktop.main.js:75 [Extension Host] [vscode-icons] v11.10.0 activated!
workbench.desktop.main.js:578   ERR Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
    at onDidChangeTextDocument (/Users/abhishek/.vscode/extensions/floookay.vscode-wpm-monitor-0.4.0/out/extension.js:124:41)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
    at y.$acceptDirtyStateChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:71246)
    at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13801)
    at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13485)
    at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:12147)
    at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:10825)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:8934
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:34390
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)
    at a._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:23583)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:21117
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
    at _.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:15833)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:14963
    at Socket.A (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:13838)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
workbench.desktop.main.js:75 [Extension Host] jsxBracketSameLine is deprecated.
I @ workbench.desktop.main.js:75
workbench.desktop.main.js:578   ERR Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
    at onDidChangeTextDocument (/Users/abhishek/.vscode/extensions/floookay.vscode-wpm-monitor-0.4.0/out/extension.js:124:41)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
    at y.$acceptDirtyStateChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:71246)
    at y.$acceptModelSaved (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:70989)
    at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13801)
    at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13485)
    at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:12147)
    at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:10825)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:8934
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:34390
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)
    at a._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:23583)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:21117
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
    at _.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:15833)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:14963
    at Socket.A (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:13838)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
workbench.desktop.main.js:75 [Extension Host] [Guides] Error while sending usage statistics: Error: connect ETIMEDOUT 18.119.154.66:443
workbench.desktop.main.js:75 [Extension Host] [Guides] Usage statistics will retry in the next 5 minutes
workbench.desktop.main.js:578   ERR s.tmpDir is not a function: TypeError: s.tmpDir is not a function
    at e._sendFirstFileOnDisk (/Users/abhishek/.vscode/extensions/msjsdiag.vscode-react-native-1.9.1/dist/rn-extension.js:1:25358)
    at Timeout._onTimeout (/Users/abhishek/.vscode/extensions/msjsdiag.vscode-react-native-1.9.1/dist/rn-extension.js:1:24162)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by abhisheksahdev** [comment]
log when i ran `npm i npm`

```log
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated vscode@0.10.7: This package is deprecated in favor of @types/vscode and vscode-test. For more information please read: https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest
npm ERR! code 1
npm ERR! path /Users/abhishek/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt
npm ERR! command failed
npm ERR! command sh -c node install.js
Downloading electron-v0.37.3-darwin-arm64.zip
npm ERR! Error: GET https://github.com/electron/electron/releases/download/v0.37.3/electron-v0.37.3-darwin-arm64.zip returned 404
npm ERR! /Users/abhishek/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/install.js:22
npm ERR!   throw err
npm ERR!   ^
npm ERR!
npm ERR! Error: Failed to find Electron v0.37.3 for darwin-arm64 at https://github.com/electron/electron/releases/download/v0.37.3/electron-v0.37.3-darwin-arm64.zip
npm ERR!     at Request.<anonymous> (/Users/abhishek/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/nugget/index.js:170:61)
npm ERR!     at Request.emit (node:events:526:28)
npm ERR!     at Request.onRequestResponse (/Users/abhishek/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:526:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:482:22)
npm ERR!     at TLSSocket.emit (node:events:526:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
npm ERR!
npm ERR! Node.js v17.5.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abhishek/.npm/_logs/2022-02-17T10_05_11_736Z-debug-0.log
```

**Comment by anseki** [comment]
Hi @Abhishek12345679, thank you for the comment.
Unfortunately, it seems that the old version of Electron that the extension uses was removed from the repository.
I welcome information about any archived files.

**Comment by abhisheksahdev** [comment]
I'm sorry but what do you mean by archived files, so that i can look for them.

**Comment by anseki** [comment]
We can't download the removed file.
Then, I think that someone might know the file at another URL.

**Comment by abhisheksahdev** [comment]
ok yeah i will try to find that out.

**Comment by anseki** [comment]
I think that the extension has already finished its part since VS Code supported internal color picker.
Then, I recommend using the internal color picker instead.

**Comment by anseki** [comment]
:smile:

**Comment by abhisheksahdev** [comment]
Thank you for your extension, anseki <3.

Can you tell me, how can i turn on the in-built color picker, i haven't been able to find it.

**Comment by anseki** [comment]
You can read the document here:
https://code.visualstudio.com/updates/v1_15?ref=codebldr#_color-picker
https://code.visualstudio.com/docs/languages/html?source=post_page...#_color-picker
https://code.visualstudio.com/docs/languages/css#_syntax-coloring-color-preview

**Comment by abhisheksahdev** [comment]
Looks like it work for css, but not for TS.
Is that a thing?

**Comment by anseki** [comment]
Sorry, this is a repository of the extension.
Could you ask that to VS Code team?
https://github.com/Microsoft/vscode/issues

**Comment by abhisheksahdev** [comment]
Thanks !! I'll do that.

**Comment by anseki** [comment]
:smile: 
Could you close this issue?
