### ISSUE TITLE
[processBridge]: Error: Cannot get NPM

### ISSUE THREAD

**Issue by ponlponl123** [anseki/vscode-color#133]
- Extension Version: 0.4.5
![image](https://user-images.githubusercontent.com/55607166/173243874-94351ba6-e94d-499b-b770-cf44a734e880.png)
- NPM Version : 8.11.0

Steps to Reproduce:

1.  Select the RGB box.
2.  Ctrl + Left Shift + P
3. Type Pick Color
4. Enter

Log (All lines):
```
[processBridge]: Error: Cannot get NPM
```

![image](https://user-images.githubusercontent.com/55607166/173243261-8d001830-2972-4c64-8e43-e1020f37d2fb.png)

**Comment by anseki** [comment]
Hi @ponlponl123, thank you for the comment.
Could you show the log?

**Comment by benedery** [comment]
same

**Comment by benedery** [comment]
[processBridge]: Error: Cannot get NPM

**Comment by anseki** [comment]
Hi @benedery, thank you for the comment.
Could you give information?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by drrcool** [comment]
I get the same issue. When trying to Npm i  npm into the extension directory, the build is failing due to the electron-prebuilt dependency having no darwin ARM version available, so M1 macs can't build unless they do extra work.  If you use nvm, you can open a terminal using Rosetta, and install a version of Node on i386 (I followed the suggestions [here](https://gist.github.com/LeZuse/bf838718ff2689c5fc035c5a6825a11c) and use lts for intel) and then install a version for arm.  Then you can manually use the intel version of node to build the package.  Seems to work so far as a workaround.

**Comment by anseki** [comment]
Hi @drrcool, thank you for the information. :smile:

**Comment by ponlponl123** [comment]
> Hi @ponlponl123, thank you for the comment. Could you show the log?

```
[2022-06-20 20:30:43.242] [renderer1] [error] [Extension Host] Error: Cannot get NPM
	at initModule (c:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:28)
	at getHostCmd (c:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
	at c:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at Object.exports.sendRequest (c:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (c:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (c:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at o._executeContributedCommand (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:62521)
	at o.$executeContributedCommand (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:63225)
	at s._doInvokeHandler (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13828)
	at s._invokeHandler (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13512)
	at s._receiveRequest (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:12173)
	at s._receiveOneMessage (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:10843)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:8949
	at g.invoke (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at a.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19025)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:34863
	at g.invoke (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at a.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19025)
	at r._receiveMessage (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23606)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21140
	at g.invoke (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at v.acceptChunk (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15856)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14986
	at Socket.R (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13798)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by anseki** [comment]
That seems a part of log.

**Comment by ivandacosta** [comment]
:( 
workbench.desktop.main.js:71 [Extension Host] Error: Cannot get NPM	at initModule (c:\Users\Ivand\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:28)	at getHostCmd (c:\Users\Ivand\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)	at c:\Users\Ivand\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19	at Object.exports.sendRequest (c:\Users\Ivand\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)	at pickConvert (c:\Users\Ivand\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)	at c:\Users\Ivand\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:245:1	at processTicksAndRejections (node:internal/process/task_queues:96:5)
I @ workbench.desktop.main.js:71
workbench.desktop.main.js:802 [processBridge]: Error: Cannot get NPM

**Comment by anseki** [comment]
Hi @ivandacosta, thank you for the comment.
Could you give information?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by cwtaras** [comment]
- Extension Version:
- VS Code Version: 1.68.1
- OS Version: macOS Monterey 12.4 (21F79) (M1 2020)
- Node.js Version (result of command `node -v`): v16.15.1
- NPM Version (result of command `npm -v`): 8.11.0

Steps to Reproduce:

1.  Open Command Palette
2. Choose Pick Color

Log (All lines): console.ts:137 [Extension Host] Error: Cannot get NPM	at initModule (/Users/bugraelmas/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:220:28)	at getHostCmd (/Users/bugraelmas/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:331:9)	at /Users/bugraelmas/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19	at Object.exports.sendRequest (/Users/bugraelmas/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)	at pickConvert (/Users/bugraelmas/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)	at exports.pick (/Users/bugraelmas/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)	at o._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:62521)	at o.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:63225)	at s._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:13828)	at s._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:13512)	at s._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:12173)	at s._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:10843)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:8949	at g.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)	at b.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:34863	at g.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)	at b.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)	at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23606)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21140	at g.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)	at b.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)	at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15856)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14986	at Socket.R (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:13798)	at Socket.emit (node:events:390:28)	at addChunk (node:internal/streams/readable:315:12)	at readableAddChunk (node:internal/streams/readable:289:9)	at Socket.Readable.push (node:internal/streams/readable:228:10)	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
I @ console.ts:137
notificationsAlerts.ts:42 [processBridge]: Error: Cannot get NPM
onDidChangeNotification @ notificationsAlerts.ts:42

**Comment by anseki** [comment]
Hi @cwtaras, thank you for the comment.
That seems a part of log.

**Comment by ponlponl123** [comment]
Here are all the results in my **Log (window)**, _(I'm not sure if this is correct)_
```
[2022-06-23 18:25:04.530] [renderer1] [critical] Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookDocumentEvents' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[2022-06-23 18:25:04.530] [renderer1] [critical] Extension 'tabnine.tabnine-vscode' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[2022-06-23 18:25:04.552] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.codelens.npmScripts'. This property is already registered.
[2022-06-23 18:25:04.553] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.terminalOptions'. This property is already registered.
[2022-06-23 18:25:04.553] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.automaticallyTunnelRemoteServer'. This property is already registered.
[2022-06-23 18:25:04.553] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.debugByLinkOptions'. This property is already registered.
[2022-06-23 18:25:04.553] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.pickAndAttachOptions'. This property is already registered.
[2022-06-23 18:25:04.553] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.autoAttachFilter'. This property is already registered.
[2022-06-23 18:25:04.553] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.autoAttachSmartPattern'. This property is already registered.
[2022-06-23 18:25:04.553] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.breakOnConditionalError'. This property is already registered.
[2022-06-23 18:25:04.554] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.unmapMissingSources'. This property is already registered.
[2022-06-23 18:25:04.554] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.defaultRuntimeExecutable'. This property is already registered.
[2022-06-23 18:25:04.554] [renderer1] [warning] [ms-vscode.js-debug-nightly]: Cannot register 'debug.javascript.resourceRequestOptions'. This property is already registered.
[2022-06-23 18:25:04.554] [renderer1] [warning] [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
[2022-06-23 18:25:04.613] [renderer1] [info] [GitHub.vscode-pull-request-github]: `remoteHub/pullRequest` is not a valid menu identifier
[2022-06-23 18:25:04.691] [renderer1] [error] [ms-vscode.js-debug-nightly]: Cannot register multiple views with same id `jsBrowserBreakpoints`
[2022-06-23 18:25:04.691] [renderer1] [error] [ms-vscode.js-debug-nightly]: Cannot register multiple views with same id `jsExcludedCallers`
[2022-06-23 18:25:05.037] [renderer1] [error] [xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
[2022-06-23 18:25:05.611] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\your pc name\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\out\extension
[2022-06-23 18:25:05.611] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\your pc name\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\out\extension
[2022-06-23 18:25:05.612] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\your pc name\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\out\extension
[2022-06-23 18:25:05.612] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\your pc name\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\out\extension
[2022-06-23 18:25:05.612] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\your pc name\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\out\extension
[2022-06-23 18:25:05.612] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\your pc name\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\out\extension
[2022-06-23 18:25:05.612] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\your pc name\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\out\extension
[2022-06-23 18:25:05.612] [renderer1] [error] [Extension Host] Failed to load message bundle for file c:\Users\your pc name\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.0.0\out\extension
[2022-06-23 18:25:05.613] [renderer1] [error] [Extension Host] (node:7536) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-06-23 18:25:08.374] [renderer1] [error] [Extension Host] validating c:\Users\your pc name\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.42\x86_64-pc-windows-gnu\TabNine.exe timeout
[2022-06-23 18:25:10.384] [renderer1] [error] [Extension Host] validating c:\Users\your pc name\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.4.40\x86_64-pc-windows-gnu\TabNine.exe timeout
[2022-06-23 18:25:29.125] [renderer1] [error] [Extension Host] Error: Cannot get NPM
	at initModule (c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:28)
	at getHostCmd (c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
	at c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at Object.exports.sendRequest (c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at o._executeContributedCommand (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:62521)
	at o.$executeContributedCommand (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:63225)
	at s._doInvokeHandler (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13828)
	at s._invokeHandler (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13512)
	at s._receiveRequest (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:12173)
	at s._receiveOneMessage (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:10843)
	at c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:8949
	at g.invoke (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at a.fire (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19025)
	at c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:34863
	at g.invoke (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at a.fire (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19025)
	at r._receiveMessage (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23606)
	at c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21140
	at g.invoke (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at v.acceptChunk (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15856)
	at c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14986
	at Socket.R (c:\Users\your pc name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13798)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by anseki** [comment]
@ponlponl123, maybe that is not all of the log.
Anway, try this:
```
cd c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5
npm install npm@6.14.11
```
And restart VS Code, and run the extension.

**Comment by ponlponl123** [comment]
> @ponlponl123, maybe that is not all of the log. Anway, try this:
> 
> ```
> cd c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5
> npm install npm@6.14.11
> ```
> 
> And restart VS Code, and run the extension.

Pick Color seems to be working now.
But Convert Color still doesn't work.
While Pick Color doesn't show up or become invisible.
`Yes, I mean when invoked Pick Color the Cursor can be dragged on the invisible window and the rgb value has changed as well.`

https://user-images.githubusercontent.com/55607166/175350565-ae389943-1259-4ad1-bbee-33b88ce1396f.mp4

**Comment by ponlponl123** [comment]
Thanks @anseki and everyone!
**Solution (for me)**
1. New Terminal
2. and type this command
```
cd c:\Users\your pc name\.vscode\extensions\anseki.vscode-color-0.4.5
npm install npm@6.14.11
```

If the Pick Color window is invisible, try this.

1. **Extension Setting**: Color Picker
2. On the topic **Color Helper: Disable Transparent**
3. Enable the **Disable transparent window.**

**more**
Convert Color cannot be used with rgb(red green blue / opacity) e.g. rgb(255 255 255 / 50%).
the right way
rgba(255, 255, 255, 0.5)

![image](https://user-images.githubusercontent.com/55607166/175355031-32d5435b-3bed-45c0-bf66-357c869835a4.png)
![image](https://user-images.githubusercontent.com/55607166/175356579-5f66e002-0127-422d-b7f1-ed5ce067418f.png)

**Comment by anseki** [comment]
:smile:

**Comment by vdawg-git** [comment]
I get the same issue and downgrading `npm` breaks my build, so this is not a solution.

**Comment by anseki** [comment]
Hi @v-dawg, thank you for the comment.
You don't have to downgrade NPM in your system. You might have mistaken the commands to install it locally.

**Comment by vluzrmos** [comment]
In my case the package is conflicting with "PostCss Language Support" (csstools.postcss), I just disable that.

**Comment by anseki** [comment]
Hi @vluzrmos, thank you for the information. :smile:
