### ISSUE TITLE
Error in WSL 2: [processBridge]: Error: Child process already exited.

### ISSUE THREAD

**Issue by V19Torrent** [anseki/vscode-color#135]
- Extension Version: 0.4.5
- VS Code Version: 1.70.2
- OS Version: Ubuntu-20.04
- Node.js Version (result of command `node -v`): v16.17.0
- NPM Version (result of command `npm -v`): 8.15.0

Steps to Reproduce:

1. Alt + C P

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[2022-08-22 00:17:05.698] [renderer1] [error] [Extension Host] Error: write EPIPE
	at ChildProcess.target._send (node:internal/child_process:846:20)
	at ChildProcess.target.send (node:internal/child_process:719:19)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:418:19
	at Array.forEach (<anonymous>)
	at sendIpc (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:416:18)
	at sendMessage (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:430:7)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:529:51
	at Array.forEach (<anonymous>)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:529:23
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19
	at getHostCmd (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:365:5)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19
	at Object.exports.sendRequest (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)
	at pickConvert (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)
	at exports.pick (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)
	at a._executeContributedCommand (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:63922)
	at a.$executeContributedCommand (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:64626)
	at o._doInvokeHandler (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:13691)
	at o._invokeHandler (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:13373)
	at o._receiveRequest (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:12143)
	at o._receiveOneMessage (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:10845)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:8952
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:111:17079
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at i._receiveMessage (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:23593)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:21127
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:15837)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:14967
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p._processReadQueue (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:33811)
	at p.acceptFrame (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:33467)
	at b._acceptChunk (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:31431)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:28420
	at Socket.l (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:26303)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
[2022-08-22 00:17:05.699] [renderer1] [error] [Extension Host] Error: write EPIPE
	at ChildProcess.target._send (node:internal/child_process:846:20)
	at ChildProcess.target.send (node:internal/child_process:719:19)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:418:19
	at Array.forEach (<anonymous>)
	at sendIpc (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:416:18)
	at sendMessage (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:430:7)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:529:51
	at Array.forEach (<anonymous>)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:529:23
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19
	at getHostCmd (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:365:5)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19
	at Object.exports.sendRequest (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)
	at pickConvert (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)
	at exports.pick (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)
	at a._executeContributedCommand (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:63922)
	at a.$executeContributedCommand (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:64626)
	at o._doInvokeHandler (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:13691)
	at o._invokeHandler (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:13373)
	at o._receiveRequest (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:12143)
	at o._receiveOneMessage (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:10845)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:8952
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:111:17079
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at i._receiveMessage (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:23593)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:21127
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:15837)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:14967
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p._processReadQueue (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:33811)
	at p.acceptFrame (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:33467)
	at b._acceptChunk (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:31431)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:28420
	at Socket.l (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:26303)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
[2022-08-22 00:17:05.699] [renderer1] [error] [Extension Host] Error: write EPIPE
	at ChildProcess.target._send (node:internal/child_process:846:20)
	at ChildProcess.target.send (node:internal/child_process:719:19)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:418:19
	at Array.forEach (<anonymous>)
	at sendIpc (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:416:18)
	at sendMessage (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:430:7)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:529:51
	at Array.forEach (<anonymous>)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:529:23
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19
	at getHostCmd (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:365:5)
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19
	at Object.exports.sendRequest (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)
	at pickConvert (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)
	at exports.pick (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)
	at a._executeContributedCommand (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:63922)
	at a.$executeContributedCommand (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:64626)
	at o._doInvokeHandler (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:13691)
	at o._invokeHandler (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:13373)
	at o._receiveRequest (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:12143)
	at o._receiveOneMessage (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:10845)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:95:8952
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:111:17079
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at i._receiveMessage (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:23593)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:21127
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:15837)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:14967
	at b.invoke (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at w.deliver (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p._processReadQueue (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:33811)
	at p.acceptFrame (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:33467)
	at b._acceptChunk (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:31431)
	at /home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:28420
	at Socket.l (/home/daltonpc/.vscode-server/bin/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:69:26303)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
[2022-08-22 00:17:05.705] [renderer1] [error] [Extension Host] Error: Child process exited with code: 127
	at /home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19
	at ChildProcess.<anonymous> (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at ChildProcess.emit (node:events:390:28)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[2022-08-22 00:17:06.694] [renderer1] [error] [Extension Host] Error: Child process already exited.
	at sendIpc (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)
	at Timeout.<anonymous> (/home/daltonpc/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at listOnTimeout (node:internal/timers:557:17)
	at processTimers (node:internal/timers:500:7)

```

**Comment by anseki** [comment]
Hi @V19Torrent, thank you for the comment.
It seems to be duplicated: https://github.com/anseki/vscode-color/issues/95#issuecomment-578734193

**Comment by V19Torrent** [comment]
Executing `sudo apt-get install libgconf-2-4` did not solve the issue.

**Comment by anseki** [comment]
Could you explain that?

**Comment by V19Torrent** [comment]
I still get the same error even after running `sudo apt-get install libgconf-2-4`.

**Comment by anseki** [comment]
Sorry, we can't help you because it's not enough information.
I recommend using internal Color Picker instead because VS Code already implements it.
