### ISSUE TITLE
[processBridge]: TypeError: callback must be a function if provided

### ISSUE THREAD

**Issue by McBen** [anseki/vscode-color#136]
- Extension Version: v0.4.5
- VS Code Version: 1.71.2 
- OS Version: win
- Node.js Version: v16.9.1
- NPM Version: 7.21.1

Won't run.

Steps to Reproduce:
- command: pick color

Log
```
TypeError: callback must be a function if provided
	at EventEmitter.load (C:\Users\viert\AppData\Roaming\nvm\v16.9.1\node_modules\npm\lib\npm.js:163:13)
	at initModule (c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:233:9)
	at getHostCmd (c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
	at c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at exports.sendRequest (c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at c._executeContributedCommand (c:\Users\viert\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63770)
```

also:
```
[Extension Host] Error: Cannot find module 'npm'
Require stack:
- c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js
- c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js
- c:\Users\viert\.vscode\extensions\anseki.vscode-color-0.4.5\extension.js
- c:\Users\viert\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\viert\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
```

**Comment by anseki** [comment]
Hi @McBen, thank you for the comment.
Try this: https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209

**Comment by McBen** [comment]
adding the NPM module will fix the error message.
![grafik](https://user-images.githubusercontent.com/29117/193465086-dfb9bdca-1b73-4d22-bd06-4cc8bdf2a381.png)

But still no dialog is displayed. (only the mouse cursor switches to a cross in a specific area)

**Comment by anseki** [comment]
Try this: https://github.com/anseki/vscode-color#rendering-trouble

**Comment by McBen** [comment]
yes, disabling GPU fixed this second problem.
thx

**Comment by anseki** [comment]
:smile: 
Could you close this issue?
