### ISSUE TITLE
[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`

### ISSUE THREAD

**Issue by 66beta** [anseki/vscode-color#30]
- Extension Version: 0.4.1
- VS Code Version: 1.11.2
- OS Version: Windows 7 X64
- Node.js Version:  6.10.2
- NPM Version: 3.10.10

Steps to Reproduce:
1. install
2. ctrl+shift+p => "pick color"

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Start child process...
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Start initializing module...
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Node.js@6.5.0
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.J.i._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at getNpm (C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:139:15)
    at initModule (C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:229:24)
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:295493)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:277319)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:135077)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:135754)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Continue trying to get NPM...
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Try to get NPM via usage info.
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] NPM@3.10.10
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] NPM directory path: C:\Users\kyle\AppData\Roaming\nvm\v6.10.2\node_modules\npm
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] NPM resolved path: C:\Users\kyle\AppData\Roaming\nvm\v6.10.2\node_modules\npm\lib\npm.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Base directory path: C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Retry (Error: Cannot find module 'electron-prebuilt')
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Try to load: C:\Users\kyle\AppData\Roaming\nvm\v6.10.2\node_modules\npm\lib\utils\spawn.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\esvalidate -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\esprima\bin\esvalidate.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\esparse -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\esprima\bin\esparse.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\mkdirp -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\mkdirp\bin\cmd.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\ncp -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\ncp\bin\ncp
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\semver -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\semver\bin\semver
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\strip-indent -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\strip-indent\cli.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\rc -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\rc\index.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\sshpk-conv -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\sshpk\bin\sshpk-conv
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\sshpk-sign -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\sshpk\bin\sshpk-sign
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\sshpk-verify -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\sshpk\bin\sshpk-verify
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\uuid -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\uuid\bin\uuid
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\pretty-bytes -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\pretty-bytes\cli.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\rimraf -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\rimraf\bin.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\nugget -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\nugget\bin.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\electron-download -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-download\cli.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\extract-zip -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\extract-zip\cli.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\electron -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\cli.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\js-yaml -> C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\js-yaml\bin\js-yaml.js
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Spawn in silent-mode: C:\windows\system32\cmd.exe /d /s /c node install.js
extensionHost.ts:284 [Extension Host] vscode-color@0.4.1 C:\Users\kyle\.vscode\extensions\anseki.vscode-color-0.4.1
+-- comma-separated-values@3.6.4 
+-- js-yaml@3.8.3 
| +-- argparse@1.0.9 
| | `-- sprintf-js@1.0.3 
| `-- esprima@3.1.3 
`-- process-bridge@0.3.6 
  `-- semver@5.3.0 

extensionHost.ts:284 [Extension Host] TextEditor is closed/disposed
extensionHost.ts:284 [Extension Host] Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (C:\Users\kyle\AppData\Roaming\nvm\v6.10.2\node_modules\npm\lib\utils\lifecycle.js:255:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\Users\kyle\AppData\Roaming\nvm\v6.10.2\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)d.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
messageService.ts:126 [processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
```

Removed extension folder and re-install 3+ times T..T

**Comment by 66beta** [comment]
Excuse for my poor english~

Found the solution, works for me:

> @anseki removed unsafe commands

Looks like its **electron-prebuilt**'s bug

Thanks anseki

**Comment by anseki** [comment]
Hi @66beta, thank you for the report.

The cache data in your computer might be broken.
You can clear the cache data by this: (You should remove those before installing the extension)

1. `npm cache clean`: Remove NPM cache data.
2. `npm cache ls`: Confirm the cache data were cleared.
3. Remove Electron cache data in `C:\Users\kyle\.electron`.

**Comment by anseki** [comment]
This issue seems to have been already solved, and I close it.
