### ISSUE TITLE
Error: electron-prebuilt@0.37.3 postinstall: `node install.js`

### ISSUE THREAD

**Issue by zhangjialegh** [anseki/vscode-color#34]
- Extension Version:
- VS Code Version:
- OS Version:
- Node.js Version (7.10.0):
- NPM Version (4.5.0):

Steps to Reproduce:

1. after ctrl c  p
2. display "wait a while for installing "

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (C:\Users\zjl\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\Users\zjl\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
d.logExtensionHostMessage @ /D:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/D:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
e.doShow @ /D:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
```

**Comment by anseki** [comment]
Hi @zhangjialegh, thank you for the report.

Could you please give me more information?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

Also, see this: https://github.com/anseki/vscode-color/issues/32
