### ISSUE TITLE
Error[processBridge]: Error: Cannot get NPM

### ISSUE THREAD

**Issue by pbaksa** [anseki/vscode-color#43]
- Extension Version: 0.4.1
- VS Code Version: 1.13.0
- OS Version: Win10
- Node.js Version (result of command `node -v`): nothing
- NPM Version (result of command `npm -v`): nothing

I don't know why I should have Node and NPM installed, VScode reports Node 7.4.0 in Help/About.

Steps to Reproduce:

1.  install package
2. ALT+C, P

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
[C:\Users\pbaksa\.vscode\extensions\fknop.vscode-npm-3.3.0]: Command `npm-script.start` appears multiple times in the `commands` section.
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\pbaksa\.vscode\extensions\fknop.vscode-npm-3.3.0]: Command `npm-script.test` appears multiple times in the `commands` section.
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Overwriting extension <<.xml>> to now point to mime <<text/x-gdl>>
(anonymous) @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  bookmarks.toggle
e._assertNoCtrlAlt @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  bookmarks.jumpToNext
e._assertNoCtrlAlt @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  bookmarks.jumpToPrevious
e._assertNoCtrlAlt @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: ENOENT: no such file or directory, scandir 'C:\Users\pbaksa\AppData\Local\GitHub'
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Start child process...
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Start initializing module...
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Node.js@7.4.0
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Q.o._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:411703)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getNpm (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:139:15)
    at initModule (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:468:34)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Continue trying to get NPM...
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Try to get NPM via usage info.
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: Command failed: npm help
'npm' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:152:27
    at getNpm (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:161:11)
    at initModule (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:187:15)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Try to get NPM via command path.
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: Command failed: where npm
INFO: Could not find files for the given pattern(s).

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:172:22
    at getNpm (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:184:11)
    at initModule (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:187:15)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Try to get NPM in global directory.
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: Command failed: npm root -g
'npm' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at getNpm (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:195:11)
    at initModule (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:229:24)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Try to get NPM via node path.
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: Command failed: node -p "process.execPath"
'node' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:203:22
    at getNpm (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:205:11)
    at initModule (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:187:15)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: Cannot get NPM
    at initModule (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:220:28)
    at getHostCmd (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\pbaksa\.vscode\extensions\anseki.vscode-color-0.4.1\lib\color-helper.js:229:24)
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:330741)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:312304)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:176531)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:177208)
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [processBridge]: Error: Cannot get NPM

**Comment by anseki** [comment]
Hi @retepaskab, thank you for the comment.

As the document (https://github.com/anseki/vscode-color#install) explained, the extension never work without Node.js and NPM.
The Node.js you saw in "Help/About" is a part of Electron, it is not standard Node.js that we can use.

**Comment by anseki** [comment]
Unfortunately, no reply came, and I close this issue.
