### ISSUE TITLE
Not sure if it's a VSCode issue...

### ISSUE THREAD

**Issue by lincolnpjames** [anseki/vscode-color#46]
- Extension Version: 0.4.1
- VS Code Version: 1.13.1
- OS Version: macOS 10.12.5
- Node.js Version (result of command `node -v`): 8.1.2
- NPM Version (result of command `npm -v`): 5.0.3

Steps to Reproduce:

1. CMD + Shift + P
2. Color Picker

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Error: ENOENT: no such file or directory, open [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Attribute using recommended pattern"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Class"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "do...while loop"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Enum"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Exception"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Foreach statement"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Reverse for loop"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "for loop"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "if statement"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Indexer"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Interface"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Safely invoking an event"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Simple iterator"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Named iterator/indexer pair using a nested class"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Lock statement"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "MessageBox.Show"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Namespace"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "#if"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "#region"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Property and backing field"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "propg"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "prop"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Struct"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Switch statement"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Try finally"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Try catch"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "Using statement"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:28 [/Users/{userdir}/.vscode/extensions/ms-vscode.csharp-1.10.0]: The "While loop"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ workbench.main.js:28
workbench.main.js:29 [Extension Host] Start child process...
workbench.main.js:29 [Extension Host] Error: ENOENT: no such file or directory, open '/Users/{userdir}/.vscode/extensions/anseki.vscode-color-0.4.1/node_modules/electron-prebuilt/path.txt'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.<anonymous> (/Users/{userdir}/.vscode/extensions/anseki.vscode-color-0.4.1/node_modules/electron-prebuilt/index.js:4:42)
    at Object.<anonymous> (/Users/{userdir}/.vscode/extensions/anseki.vscode-color-0.4.1/node_modules/electron-prebuilt/index.js:6:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:28 [processBridge]: Error: ENOENT: no such file or directory, open '/Users/{userdir}/.vscode/extensions/anseki.vscode-color-0.4.1/node_modules/electron-prebuilt/path.txt'
```

Note: My username is replaced with: {userdir}

**Comment by lincolnpjames** [comment]
It was an issue with my installation - Please ignore

**Comment by anseki** [comment]
😄
