### ISSUE TITLE
[processBridge]: Error: ENOENT: no such file or directory, open 'C:\Users\svict\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'

### ISSUE THREAD

**Issue by svictoreq** [anseki/vscode-color#48]
- Extension Version: **0.4.1**
- VS Code Version: **1.13.1**
- OS Version: Windows 10 **Version 1703 Build 15063.413**
- Node.js Version (result of command `node -v`):  **v6.11.0**
- NPM Version (result of command `npm -v`): **3.10.10**

Steps to Reproduce:

1.  Execute the extension via Alt + C P or via Command Palette (Pick Color)

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Error: ENOENT: no such file or directory, open 'C:\Users\svict\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.<anonymous> (C:\Users\svict\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\index.js:4:42)
    at Object.<anonymous> (C:\Users\svict\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\index.js:6:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Q.o._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:411703)
    at Module.require (module.js:498:17)
    at getHostCmd (C:\Users\svict\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:316:41)
    at C:\Users\svict\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\svict\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\process-bridge\process-bridge.js:468:34)
```

**Comment by svictoreq** [comment]
I have reinstalled the extension but nothing seems to work...

**Comment by anseki** [comment]
Hi @svictoreq, thank you for the comment.

It seems that the installation failed.
And cache data in your computer might be broken.
You can clear the cache data by this:

1. Uninstall the extension.
2. Command to remove NPM cache data.  
`npm cache clean`
3. Command to confirm the cache data were cleared.  
`npm cache ls`
4. Remove Electron cache data in:  
`"%USERPROFILE%\.electron"` (Windows)  
`~/.electron` (others)
5. Re-install the extension.

**Comment by svictoreq** [comment]
I did what you told me to do, and it's 4 hours now, and still "setting up the extension". Is that normal?
![image](https://user-images.githubusercontent.com/29575744/27450698-8a1dbc42-575a-11e7-9f58-ec083719252f.png)

**Comment by anseki** [comment]
Maybe your network line has problem. For example, you might be in China.
See: [Manual installation NPM modules](https://github.com/anseki/vscode-color#manual-installation-npm-modules)

**Comment by svictoreq** [comment]
I am trying that but it doesn't install.
I'm in the **anseki.vscode-color-0.4.1** directory and using npm install.
My system is 64-bits. Does that matter?
I'm in Venezuela...

**Comment by anseki** [comment]
Please details.
What happened by `npm install`?
E.g. an error message was shown?

**Comment by svictoreq** [comment]
No error was displayed, I think it was the internet connection...
I tried the `npm install` command again and it worked... 
The extension was invisible, but I changed the `"colorHelper.disableTransparent"` to `true` and it's working perfect right now. 
Thanks, great support!

**Comment by anseki** [comment]
😄
