### ISSUE TITLE
Color Picker [processBridge]: Error: Cannot get NPM

### ISSUE THREAD

**Issue by alayat** [anseki/vscode-color#56]
- Extension Version: 0.4.5
- VS Code Version: 1.15.1 64-bit stable
- OS Version: 7 64-bit
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):

Steps to Reproduce:

1. When entering the command Ctrl + C P sends the error [processBridge]: Error: Cannot get npm

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Error: ENOENT: no such file or directory, scandir 'C:\Users\Dev Ahmed\AppData\Local\GitHub'
t.logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Start child process...
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Start initializing module...
t.logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Node.js@7.4.0
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.G.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:404827)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getNpm (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:139:15)
    at initModule (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328925)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Continue trying to get NPM...
t.logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Try to get NPM via usage info.
t.logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Error: Command failed: npm help
'npm' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:152:27
    at getNpm (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:161:11)
    at initModule (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328925)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Try to get NPM via command path.
t.logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Error: Command failed: where npm
INFO: Could not find files for the given pattern(s).

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:172:22
    at getNpm (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:184:11)
    at initModule (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328925)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Try to get NPM in global directory.
t.logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Error: Command failed: npm root -g
'npm' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at getNpm (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:195:11)
    at initModule (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328925)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Try to get NPM via node path.
t.logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Error: Command failed: node -p "process.execPath"
'node' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:203:22
    at getNpm (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:205:11)
    at initModule (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328925)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29 [Extension Host] Error: Cannot get NPM
    at initModule (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:28)
    at getHostCmd (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
    at exports.pick (C:\Users\Dev Ahmed\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328925)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
t.logExtensionHostMessage @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28 [processBridge]: Error: Cannot get NPM
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28

**Comment by anseki** [comment]
Hi @alayat,

You didn't write versions of Node.js and NPM.
Do you have those?
See: https://github.com/anseki/vscode-color#install

**Comment by anseki** [comment]
No reply came. I close this issue.
