### ISSUE TITLE
Error: child process already exists.

### ISSUE THREAD

**Issue by rawnly** [anseki/vscode-color#62]
- Extension Version: 0.4.5
- VS Code Version: 1.17.2
- OS Version: MacOS 10.13
- Node.js Version (result of command `node -v`): 8.7.0
- NPM Version (result of command `npm -v`): 5.4.2

Steps to Reproduce:

1. Install the plugin
2. Use it.

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
extensionService.ts:433 [/Users/rawnly/.vscode/extensions/hollowtree.vue-snippets-0.1.5]: Unknown language in `contributes.vue-snippets.language`. Provided value: pug
e._logMessageInConsole @ extensionService.ts:433
console.ts:123 [Extension Host] Start child process...
console.ts:123 [Extension Host] Start initializing module...
t.log @ console.ts:123
console.ts:123 [Extension Host] Node.js@7.9.0
console.ts:123 [Extension Host] Error: Cannot find module 'npm'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.X.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:422043)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at getNpm (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:139:15)
	at initModule (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:220:10)
	at getHostCmd (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:331:9)
	at /Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19
	at Object.exports.sendRequest (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)
	at pickConvert (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)
	at exports.pick (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:348471)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:444706)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290666)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290356)
console.ts:123 [Extension Host] Continue trying to get NPM...
t.log @ console.ts:123
console.ts:123 [Extension Host] Try to get NPM via usage info.
t.log @ console.ts:123
console.ts:123 [Extension Host] NPM@5.4.2
console.ts:123 [Extension Host] NPM directory path: /Users/rawnly/.nvm/versions/node/v8.7.0/lib/node_modules/npm
console.ts:123 [Extension Host] NPM resolved path: /Users/rawnly/.nvm/versions/node/v8.7.0/lib/node_modules/npm/lib/npm.js
console.ts:123 [Extension Host] Base directory path: /Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5
console.ts:123 [Extension Host] Retry (Error: Cannot find module 'electron-prebuilt')
t.log @ console.ts:123
console.ts:123 [Extension Host] Try to load: /Users/rawnly/.nvm/versions/node/v8.7.0/lib/node_modules/npm/lib/utils/spawn.js
t.log @ console.ts:123
console.ts:123 [Extension Host] added 153 packages, removed 1 package and updated 1 package in 4.821s
console.ts:123 [Extension Host] Check version of: electron-prebuilt
console.ts:123 [Extension Host] Check version of: comma-separated-values
console.ts:123 [Extension Host] Check version of: js-yaml
console.ts:123 [Extension Host] Check version of: process-bridge
console.ts:123 [Extension Host] Try to send IPC message: 1
console.ts:123 [Extension Host] [STDERR]: module.js:340
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     throw err;
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     ^
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]: Error: Cannot find module 'electron'
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module._resolveFilename (module.js:338:15)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module._load (module.js:289:25)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Module.require (module.js:366:17)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at require (module.js:385:17)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Object.<anonymous> (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/lib/app.asar/main.js:3:12)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Module._compile (module.js:425:26)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Object.Module._extensions..js (module.js:432:10)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Module.load (module.js:356:32)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module._load (module.js:313:12)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module.runMain (module.js:457:10)
t.log @ console.ts:123
console.ts:123 [Extension Host] Child process disconnected
console.ts:123 [Extension Host] Child process exited with code: 1
console.ts:123 [Extension Host] Error: Child process exited with code: 1
	at /Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19
	at ChildProcess.<anonymous> (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
t.log @ console.ts:123
messageService.ts:125 [processBridge]: Error: Child process exited with code: 1
e.doShow @ messageService.ts:125
console.ts:123 [Extension Host] Error: Child process already exited.
	at sendIpc (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)
	at Timeout.<anonymous> (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
t.log @ console.ts:123
messageService.ts:125 [processBridge]: Error: Child process already exited.
e.doShow @ messageService.ts:125
console.ts:123 [Extension Host] Start child process...
console.ts:123 [Extension Host] Check version of: electron-prebuilt
console.ts:123 [Extension Host] Check version of: comma-separated-values
console.ts:123 [Extension Host] Check version of: js-yaml
console.ts:123 [Extension Host] Check version of: process-bridge
console.ts:123 [Extension Host] Try to send IPC message: 1
console.ts:123 [Extension Host] Try to send IPC message: 2
console.ts:123 [Extension Host] [STDERR]: module.js:340
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     throw err;
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     ^
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]: Error: Cannot find module 'electron'
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module._resolveFilename (module.js:338:15)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module._load (module.js:289:25)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Module.require (module.js:366:17)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at require (module.js:385:17)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Object.<anonymous> (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/lib/app.asar/main.js:3:12)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Module._compile (module.js:425:26)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Object.Module._extensions..js (module.js:432:10)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Module.load (module.js:356:32)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module._load (module.js:313:12)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module.runMain (module.js:457:10)
t.log @ console.ts:123
console.ts:123 [Extension Host] Child process disconnected
console.ts:123 [Extension Host] Child process exited with code: 1
console.ts:123 [Extension Host] Error: Child process exited with code: 1
	at /Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19
	at ChildProcess.<anonymous> (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
t.log @ console.ts:123
messageService.ts:125 [processBridge]: Error: Child process exited with code: 1
e.doShow @ messageService.ts:125
console.ts:123 [Extension Host] Error: Child process already exited.
	at sendIpc (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)
	at Timeout.<anonymous> (/Users/rawnly/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
t.log @ console.ts:123
messageService.ts:125 [processBridge]: Error: Child process already exited.
```

<img width="1178" alt="screen shot 2017-10-19 at 23 42 43" src="https://user-images.githubusercontent.com/16429579/31795833-97b03238-b527-11e7-9390-e0c75fafb1d1.png">

?

**Comment by anseki** [comment]
Hi @Rawnly, thank you for the comment.
It seems that Electron in your computer is broken. That installation might have failed.
Try to re-install that. Also, clear the cache data.

1. Uninstall the extension.
2. Command to remove NPM cache data.  
`npm cache clean`
3. Command to confirm the cache data were cleared.  
`npm cache ls`
4. Remove Electron cache data in `~/.electron`.
5. Re-install the extension.

**Comment by rawnly** [comment]
It didn't solve it.. Still get same errors. 


With node 8 (without extension):
- `npm cache verify`
- deleted `~/.electron` folder.
- install the extension 

With node 6:
1. `npm cache clean`
2.`npm cache ls` => ~/.npm 
3. deleted the `~/.electron` folder
4. Try again but nothing changed.

![vspicker](https://user-images.githubusercontent.com/16429579/31817812-ccd9a994-b595-11e7-8049-ec045fa0c64b.gif)

**Comment by anseki** [comment]
I see.
Multiple versions of Node.js were installed in your computer, right?
The Electron and another Electron might conflict if you have installed Electron globally before.
That should not be installed globally because various apps may not work by the confliction.
Try to remove that. (except there are special reasons)

First, activate a version of NPM that VS Code uses.

```
npm uninstall -g electron
npm uninstall -g electron-prebuilt

cd ~/.vscode/extensions/anseki.vscode-color-0.4.5
npm uninstall electron-prebuilt
```

And execute `Pick Color` command on VS Code.

**Comment by rawnly** [comment]
I don't have electron installed globally, but I will care about that thanks. However I got a new error:

`[processBridge]: Error: 'options.hostModule' and 'package.json' are required.`

**Comment by anseki** [comment]
I recommend you to check that because Electron might have been installed unintentionally.
And, that new error shows that the extension is broken. Re-install that.

**Comment by rawnly** [comment]
As you can see there is no electron, (it's a new machine so I'm pretty sure about that )

![screen shot 2017-10-20 at 17 44 46](https://user-images.githubusercontent.com/16429579/31829707-651fc774-b5be-11e7-8099-daf96e6739d9.png)
![screen shot 2017-10-20 at 17 47 41](https://user-images.githubusercontent.com/16429579/31829862-d2a97632-b5be-11e7-824c-176f1c1764c4.png)


However I'll try to reinstall it.

EDIT:
Still get the same error.

**Comment by anseki** [comment]
So, this issue is caused by the error as the message "Cannot find module 'electron'" in the log.
Could you show me new log?

**Comment by rawnly** [comment]
Oh now it's working, I've just restarted my macbook.. thanks so much for support!

**Comment by anseki** [comment]
😄 
I think, the Electron was repaired by re-installing, and one of multiple versions of Node.js was restored in the process that VS Code uses by rebooting OS.
