### ISSUE TITLE
Cannot find module electron

### ISSUE THREAD

**Issue by raldred** [anseki/vscode-color#66]
I have never had color picker installed on this machine.

- Extension Version: 0.4.5
- VS Code Version: 1.19.1
- OS Version: macOS 10.12.6
- Node.js Version (result of command `node -v`): 9.3.0
- NPM Version (result of command `npm -v`): 5.6.0

Steps to Reproduce:

1. Installed color picker from extensions panel 
2. Tried combination key Alt C P and Color Pick command but both produce the following error in the VS code dev tools console

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```

console.ts:123 [Extension Host] [STDERR]:     throw err;
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     ^
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]: Error: Cannot find module 'electron'
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module._resolveFilename (module.js:338:15)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Function.Module._load (module.js:289:25)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Module.require (module.js:366:17)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at require (module.js:385:17)
t.log @ console.ts:123
console.ts:123 [Extension Host] [STDERR]:     at Object.<anonymous> (/Users/rob/.vscode/extensions/anseki.vscode-color-0.4.5/lib/app.asar/main.js:3:12)
[Extension Host] Error: Child process exited with code: 1
	at /Users/rob/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19
	at ChildProcess.<anonymous> (/Users/rob/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by anseki** [comment]
Hi @raldred, thank you for the report.
So, is that all of the log? I guess that more messages were shown.

**Comment by anseki** [comment]
No reply came. I close this issue.
