### ISSUE TITLE
picker color no response, I guess if have relation to my setting   css.colorDecorators:false

### ISSUE THREAD

**Issue by mask2012** [anseki/vscode-color#75]
- Extension Name: vscode-color
- Extension Version: 0.4.5
- OS Version: Windows_NT x64 6.1.7601
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 6,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "onCommand:extension.colorHelper.pick"
	}
}
```

**Comment by anseki** [comment]
Hi @mask2012, thank you for the report.
Could you give me more information including "Steps to Reproduce", etc,?
See: https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by mask2012** [comment]
### Steps to Reproduce:
1.alt+c p  try to call color-picker

### log:
INFO no standard startup: panel is active
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Start child process...
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Start initializing module...
t.log @ /C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Node.js@8.9.3
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Error: Cannot find module 'npm'
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.t._load (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:268)
	at Function.o._load (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:563)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at getNpm (C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:139:15)
	at initModule (C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)
	at getHostCmd (C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
	at C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at Object.exports.sendRequest (C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at e._executeContributedCommand (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:706)
	at e.$executeContributedCommand (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:453:212)
	at t._doInvokeHandler (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Continue trying to get NPM...
t.log @ /C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Try to get NPM via usage info.
t.log @ /C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] NPM@6.4.1
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] NPM directory path: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] NPM resolved path: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\npm.js
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Base directory path: C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Retry (Error: Cannot find module 'electron-prebuilt')
t.log @ /C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
/C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Try to load: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js
t.log @ /C:/Users/Administrator/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\esvalidate -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\esprima\bin\esvalidate.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\esparse -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\esprima\bin\esparse.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\mkdirp -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\mkdirp\bin\cmd.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\ncp -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\ncp\bin\ncp
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\semver -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\semver\bin\semver
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\strip-indent -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\strip-indent\cli.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\rc -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\rc\cli.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\sshpk-conv -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\sshpk\bin\sshpk-conv
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\sshpk-verify -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\sshpk\bin\sshpk-verify
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\sshpk-sign -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\sshpk\bin\sshpk-sign
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\uuid -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\uuid\bin\uuid
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\pretty-bytes -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\pretty-bytes\cli.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\rimraf -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\rimraf\bin.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\nugget -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\nugget\bin.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\electron-download -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-download\cli.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\extract-zip -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\extract-zip\cli.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\electron -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\cli.js
workbench.main.js:sourcemap:282 [Extension Host] C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\js-yaml -> C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\js-yaml\bin\js-yaml.js
workbench.main.js:sourcemap:3156 Extension Host
workbench.main.js:sourcemap:3156 Downloading electron-v0.37.3-win32-x64.zip
[>                                            ] 0.0% (0 B/s)

workbench.main.js:sourcemap:3156 Extension Host
workbench.main.js:sourcemap:3156 [1000D[0K[1A[1000D[0K[1A[1000D[0KDownloading electron-v0.37.3-win32-x64.zip
Error: connect ETIMEDOUT 52.216.132.139:443
C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\install.js:22
  throw err
  ^

Error: connect ETIMEDOUT 52.216.132.139:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

workbench.main.js:sourcemap:282 [Extension Host] Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
	at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
	at emitTwo (events.js:126:13)
	at EventEmitter.emit (events.js:214:7)
	at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
	at emitTwo (events.js:126:13)
	at ChildProcess.emit (events.js:214:7)
	at maybeClose (internal/child_process.js:925:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
t.log @ workbench.main.js:sourcemap:282
t._logExtensionHostMessage @ workbench.main.js:sourcemap:3160
(anonymous) @ workbench.main.js:sourcemap:3156
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:sourcemap:2374 [processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js` Exit status 1

**Comment by anseki** [comment]
Node.js Version and NPM Version?
See: https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by mask2012** [comment]
finally I know why, 
npm package downloading error, because in china npm is always slow or forbidden, and I tried several ways, and finally get it done!  thank you so much!

**Comment by anseki** [comment]
:smile:
So, could you close this issue if it was solved?
