### ISSUE TITLE
Color picker does not work on remote SSH profile "Error: Child process exited with code: 127"

### ISSUE THREAD

**Issue by MurphyPone** [anseki/vscode-color#94]
- Extension Version: 0.4.5
- VS Code Version: 1.41.1 
- OS Version: Mojave 10.14.5
- Node.js Version: 11.14.0
- NPM Version: 6.7.0

Steps to Reproduce:

1. SSH into remote host
2. Install Color Picker
3. From Command Pallet select `Pick Color`

Log (All lines):
```
[Extension Host] Cannot execute extension.colorHelper because there is no active text editor.
[Extension Host] Info Python Extension: 2020-01-14 11:23:49: Cached data exists getEnvironmentVariables, /home/peter.murphy/PyTorch-basics
[Extension Host] Start child process...
[Extension Host] Check version of: electron-prebuilt
[Extension Host] Check version of: comma-separated-values
[Extension Host] Check version of: js-yaml
[Extension Host] Check version of: process-bridge
[Extension Host] Try to send IPC message: 1
[Extension Host] Try to send IPC message: 2
[Extension Host] Try to send IPC message: 3
[Extension Host] Try to send IPC message: 4
[Extension Host] Try to send IPC message: 5
[Extension Host] [STDERR]: /home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

[Extension Host] Child process disconnected
[Extension Host] Child process exited with code: 127
[Extension Host] Error: Child process exited with code: 127	
at /home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19	
at ChildProcess.<anonymous> (/home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	
at ChildProcess.emit (events.js:200:13)	
at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

[processBridge]: Error: Child process exited with code: 127
onDidNotificationChange @ notificationsAlerts.ts:40
 [Extension Host] Error: Child process already exited.	
at sendIpc (/home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)	
at Timeout.<anonymous> (/home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	
at listOnTimeout (internal/timers.js:531:17)	
at processTimers (internal/timers.js:475:7)

[processBridge]: Error: Child process already exited.
ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

Upon selecting `Pick Color`  from the Command Pallet or entering the shortcut,  these windows pop-up as well:
![image](https://user-images.githubusercontent.com/17102913/72362518-54f2ae80-36c1-11ea-9d48-10bc0e9d8c7a.png)

Any suggestions are much appreciated!

**Comment by anseki** [comment]
Hi @MurphyPone, thank you for the comment.
Try this to install that:
```
sudo apt-get install libgconf-2-4
```
And, execute the extension again after installation that.

**Comment by MurphyPone** [comment]
Installed libgconf-2-4 and am now receiving the error: `[processBridge]: Error: Child process exited with code: 1`.  I followed the advice provided in #74 (uninstalling electron, clearing the npm cashe, etc.), but still receive the same error.  The full error log is provided below:

 ```
[Extension Host] (node:96204) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[Extension Host] Start child process...
 [Extension Host] Check version of: electron-prebuilt
[Extension Host] Check version of: comma-separated-values
[Extension Host] Check version of: js-yaml
[Extension Host] Check version of: process-bridge
[Extension Host] Try to send IPC message: 1
[Extension Host] Child process disconnected
[Extension Host] Child process exited with code: 1
[Extension Host] Error: Child process exited with code: 1	
at /home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19	
at ChildProcess.<anonymous> (/home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	
at ChildProcess.emit (events.js:200:13)	
at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[processBridge]: Error: Child process exited with code: 1
[Extension Host] Error: Child process already exited.	
at sendIpc (/home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)	
at Timeout.<anonymous> (/home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	
at listOnTimeout (internal/timers.js:531:17)	
at processTimers (internal/timers.js:475:7)
[processBridge]: Error: Child process already exited. 
 ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

**Comment by anseki** [comment]
For test, try this command:
```
cd /home/peter.murphy/.vscode-server/extensions/anseki.vscode-color-0.4.5
node_modules/electron-prebuilt/dist/electron
```
This is test to start Electron, not Color Picker.
A message "Welcome to Electron" should be shown, if there is no problem.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
