### ISSUE TITLE
Picker does not shown in sway

### ISSUE THREAD

**Issue by nikto-b** [anseki/vscode-color#97]
- Extension Version: 0.4.5
- VS Code Version: 1.44.1
- OS Version: ArchLinux, Linux 5.6.4 x64
- Node.js Version: 13.13.0
- NPM Version: 6.14.4

VS Code about page:
- Version: 1.44.1
- Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
- Date: 2020-04-16T21:41:21.848Z
- Electron: 7.1.14
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Linux x64 5.6.4

OS more info:
- Intel UHD Graphics 620
- sway 1.4
- Linux 5.6.4 x86_64 GNU/Linux

Some 'special' env variables:
```
QT_QPA_PLATFORMTHEME=qt5ct
QT_QPA_PLATFORM=wayland-egl
SDL_VIDEODRIVER=wayland
_JAVA_AWT_WM_NONREPARENTING=1
CLUTTER_BACKEND=wayland
XDG_CURRENT_DESKTOM=Unity
MOZ_ENABLE_WAYLAND=1
WINIT_UNIX_BACKEND=x11
```
`colorHelper.disableGpu` set to `1`
`colorHelper.disableShadow` set to `true`
and `colorHelper.disableTransparent` set to `true`

Steps to Reproduce:

1. Open C++ Project
2. Ctrl+Shift+P
3. Type 'Pick Color' and press enter

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Error: Child process already exited.	at sendIpc (/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)	at Timeout.<anonymous> (/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	at listOnTimeout (internal/timers.js:531:17)	at processTimers (internal/timers.js:475:7)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

```
[processBridge]: Error: Child process already exited.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

**Comment by anseki** [comment]
Hi @niktob560, thank you for the comment.
Were not more log lines output?

**Comment by nikto-b** [comment]
Shure, there is a full output of console at cold start of VS code with calling a picker:
```
[Extension Host] activating extension
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] starting language server
2/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] (node:1355460) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Start child process...
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Check version of: electron-prebuilt
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Check version of: comma-separated-values
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Check version of: js-yaml
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Check version of: process-bridge
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Try to send IPC message: 1
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] [STDERR]: (electron:1355747): Pango-ERROR **: 13:08:57.382: Harfbuzz version too old (1.1.3)
t.log @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Child process disconnected
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Child process exited with code: null
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Error: Child process exited with code: null	at /home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19	at ChildProcess.<anonymous> (/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	at ChildProcess.emit (events.js:203:13)	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
t.log @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2855 [processBridge]: Error: Child process exited with code: null
onDidChangeNotification @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2855
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Error: Child process already exited.	at sendIpc (/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)	at Timeout.<anonymous> (/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	at listOnTimeout (internal/timers.js:531:17)	at processTimers (internal/timers.js:475:7)
t.log @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2855 [processBridge]: Error: Child process already exited.
onDidChangeNotification @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2855
```

**Comment by anseki** [comment]
The Electron in your computer might have a problem.
Try this:

1. Uninstall the extension via VS Code.
2. Remove this directory:  
`/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5`
3. Execute these commands in terminal app (not "TERMINAL" panel in VS Code):  
`npm uninstall -g electron`  
`npm uninstall -g electron-prebuilt`
`npm cache clean`
4. Execute this command in terminal app to confirm the cache data were cleared (i.e. no file is shown):  
`npm cache ls`
5. Remove this directory:  
`~/.electron`.
6. Press <kbd>Ctrl</kbd> + <kbd>@</kbd> keys (<kbd>Shift</kbd> key also might be required) in VS Code. Then a "TERMINAL" panel is opened.
7. In the "TERMINAL" panel above (not terminal app), execute this command:  
`node -e "console.log(require('electron-prebuilt'))"`  
Then an error `Error: Cannot find module 'electron-prebuilt'` should occur (this is correct result).
8. Re-install the extension via VS Code.

**Comment by nikto-b** [comment]
`npm cache clean` requires `--force` flag
`npm cache ls` not found:
```
$ npm cache ls
npm ERR! Usage: npm cache add <tarball file>
npm ERR! npm cache add <folder>
npm ERR! npm cache add <tarball url>
npm ERR! npm cache add <git url>
npm ERR! npm cache add <name>@<version>
npm ERR! npm cache clean
npm ERR! npm cache verify
```
Other steps passed with no errors

Error still here

```
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] activating extension
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] starting language server
2/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] (node:1738817) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Start child process...
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Check version of: electron-prebuilt
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Check version of: comma-separated-values
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Check version of: js-yaml
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Check version of: process-bridge
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Try to send IPC message: 1
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] [STDERR]: (electron:1739363): Pango-ERROR **: 17:34:27.878: Harfbuzz version too old (1.1.3)
t.log @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Child process disconnected
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Child process exited with code: null
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Error: Child process exited with code: null	at /home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19	at ChildProcess.<anonymous> (/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	at ChildProcess.emit (events.js:203:13)	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
t.log @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2855 [processBridge]: Error: Child process exited with code: null
onDidChangeNotification @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2855
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] Error: Child process already exited.	at sendIpc (/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)	at Timeout.<anonymous> (/home/nikto_b/.vscode-oss/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)	at listOnTimeout (internal/timers.js:531:17)	at processTimers (internal/timers.js:475:7)
t.log @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:262
/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2855 [processBridge]: Error: Child process already exited.
onDidChangeNotification @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2855
```

**Comment by anseki** [comment]
Hmm... If an error about a library was shown, this may solve this issue:
https://github.com/anseki/vscode-color/issues/89
However, this issue might be related to glibc. If so, it is not easy...
https://github.com/anseki/vscode-color/issues/90
Then, you had better use Color Picker of VS Code instead.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
