### ISSUE TITLE
The picker needs to support .vue files

### ISSUE THREAD

**Issue by HackerWand** [anseki/vscode-color#99]
When I was editing the.vue file, the color palette under the <style lang="less" scoped> tag could not be activated

**Comment by anseki** [comment]
Hi @HackerWand, thank you for the comment.
Vue file is already being supported.
Could you give information?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by HackerWand** [comment]
- Extension Version: 0.4.5
- VS Code Version: 1.45.1
- OS Version: macOS Catalina 10.15.1
- Node.js Version (result of command `node -v`): v10.15.3
- NPM Version (result of command `npm -v`): 6.4.1

Steps to Reproduce:

The color picker works fine when I change the current vue file syntax to HTML, but the color picker is useless when I change the vue syntax to HTML

![image](https://user-images.githubusercontent.com/12233185/82399217-3b0a1380-9a87-11ea-817c-08c9b106feae.png)


Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
workbench.desktop.main.js:sourcemap:4512 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///Users/hackerwand/.vscode/extensions/georgewfraser.vscode-javac-0.2.33/lib/java.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:4512
s @ workbench.desktop.main.js:sourcemap:4513
_getOrCreateGrammarFactory @ workbench.desktop.main.js:sourcemap:5384
async function (async)
_getOrCreateGrammarFactory @ workbench.desktop.main.js:sourcemap:5384
(anonymous) @ workbench.desktop.main.js:sourcemap:5385
_registerDefinitionIfAvailable @ workbench.desktop.main.js:sourcemap:5385
(anonymous) @ workbench.desktop.main.js:sourcemap:5382
_handle @ workbench.desktop.main.js:sourcemap:3683
acceptUsers @ workbench.desktop.main.js:sourcemap:3683
_handleExtensionPoint @ workbench.desktop.main.js:sourcemap:3918
_doHandleExtensionPoints @ workbench.desktop.main.js:sourcemap:3917
_registerAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4377
_startLocalExtensionHost @ workbench.desktop.main.js:sourcemap:4377
_scanAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4377
async function (async)
_scanAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4374
_initialize @ workbench.desktop.main.js:sourcemap:3913
(anonymous) @ workbench.desktop.main.js:sourcemap:4369
requestIdleCallback (async)
t.runWhenIdle @ workbench.desktop.main.js:sourcemap:131
(anonymous) @ workbench.desktop.main.js:sourcemap:4369
Promise.then (async)
e @ workbench.desktop.main.js:sourcemap:4369
_createInstance @ workbench.desktop.main.js:sourcemap:1625
_createServiceInstance @ workbench.desktop.main.js:sourcemap:1627
_createServiceInstanceWithOwner @ workbench.desktop.main.js:sourcemap:1626
_createAndCacheServiceInstance @ workbench.desktop.main.js:sourcemap:1626
_getOrCreateServiceInstance @ workbench.desktop.main.js:sourcemap:1625
get @ workbench.desktop.main.js:sourcemap:1624
initLayout @ workbench.desktop.main.js:sourcemap:6178
(anonymous) @ workbench.desktop.main.js:sourcemap:6266
invokeFunction @ workbench.desktop.main.js:sourcemap:1624
startup @ workbench.desktop.main.js:sourcemap:6266
open @ workbench.desktop.main.js:sourcemap:7229
async function (async)
open @ workbench.desktop.main.js:sourcemap:7229
t.main @ workbench.desktop.main.js:sourcemap:7234
(anonymous) @ workbench.js:33
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ workbench.js:29
(anonymous) @ bootstrap-window.js:130
t._invokeFactory @ loader.js:1043
t.complete @ loader.js:1053
s._onModuleComplete @ loader.js:1674
s._onModuleComplete @ loader.js:1686
s._resolve @ loader.js:1634
s.defineModule @ loader.js:1281
r @ loader.js:1724
c @ loader.js:794
(anonymous) @ workbench.desktop.main.js:sourcemap:7255
(anonymous) @ workbench.desktop.main.js:sourcemap:7255
t._createAndEvalScript @ loader.js:797
(anonymous) @ loader.js:779
u @ loader.js:892
(anonymous) @ loader.js:897
readFileAfterClose @ internal/fs/read_file_context.js:61
workbench.desktop.main.js:sourcemap:4512 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/hackerwand/.vscode/extensions/jakebathman.mysql-syntax-1.3.1/syntaxes/MySQL.tmLanguage
register @ workbench.desktop.main.js:sourcemap:4512
s @ workbench.desktop.main.js:sourcemap:4513
_getOrCreateGrammarFactory @ workbench.desktop.main.js:sourcemap:5384
async function (async)
_getOrCreateGrammarFactory @ workbench.desktop.main.js:sourcemap:5384
(anonymous) @ workbench.desktop.main.js:sourcemap:5385
_registerDefinitionIfAvailable @ workbench.desktop.main.js:sourcemap:5385
(anonymous) @ workbench.desktop.main.js:sourcemap:5382
_handle @ workbench.desktop.main.js:sourcemap:3683
acceptUsers @ workbench.desktop.main.js:sourcemap:3683
_handleExtensionPoint @ workbench.desktop.main.js:sourcemap:3918
_doHandleExtensionPoints @ workbench.desktop.main.js:sourcemap:3917
_registerAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4377
_startLocalExtensionHost @ workbench.desktop.main.js:sourcemap:4377
_scanAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4377
async function (async)
_scanAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4374
_initialize @ workbench.desktop.main.js:sourcemap:3913
(anonymous) @ workbench.desktop.main.js:sourcemap:4369
requestIdleCallback (async)
t.runWhenIdle @ workbench.desktop.main.js:sourcemap:131
(anonymous) @ workbench.desktop.main.js:sourcemap:4369
Promise.then (async)
e @ workbench.desktop.main.js:sourcemap:4369
_createInstance @ workbench.desktop.main.js:sourcemap:1625
_createServiceInstance @ workbench.desktop.main.js:sourcemap:1627
_createServiceInstanceWithOwner @ workbench.desktop.main.js:sourcemap:1626
_createAndCacheServiceInstance @ workbench.desktop.main.js:sourcemap:1626
_getOrCreateServiceInstance @ workbench.desktop.main.js:sourcemap:1625
get @ workbench.desktop.main.js:sourcemap:1624
initLayout @ workbench.desktop.main.js:sourcemap:6178
(anonymous) @ workbench.desktop.main.js:sourcemap:6266
invokeFunction @ workbench.desktop.main.js:sourcemap:1624
startup @ workbench.desktop.main.js:sourcemap:6266
open @ workbench.desktop.main.js:sourcemap:7229
async function (async)
open @ workbench.desktop.main.js:sourcemap:7229
t.main @ workbench.desktop.main.js:sourcemap:7234
(anonymous) @ workbench.js:33
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ workbench.js:29
(anonymous) @ bootstrap-window.js:130
t._invokeFactory @ loader.js:1043
t.complete @ loader.js:1053
s._onModuleComplete @ loader.js:1674
s._onModuleComplete @ loader.js:1686
s._resolve @ loader.js:1634
s.defineModule @ loader.js:1281
r @ loader.js:1724
c @ loader.js:794
(anonymous) @ workbench.desktop.main.js:sourcemap:7255
(anonymous) @ workbench.desktop.main.js:sourcemap:7255
t._createAndEvalScript @ loader.js:797
(anonymous) @ loader.js:779
u @ loader.js:892
(anonymous) @ loader.js:897
readFileAfterClose @ internal/fs/read_file_context.js:61
workbench.desktop.main.js:sourcemap:4512 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: file:///Users/hackerwand/.vscode/extensions/joshpeng.sublime-babel-vscode-0.2.10/syntaxes/sublime-babel.json
register @ workbench.desktop.main.js:sourcemap:4512
s @ workbench.desktop.main.js:sourcemap:4513
_getOrCreateGrammarFactory @ workbench.desktop.main.js:sourcemap:5384
async function (async)
_getOrCreateGrammarFactory @ workbench.desktop.main.js:sourcemap:5384
(anonymous) @ workbench.desktop.main.js:sourcemap:5385
_registerDefinitionIfAvailable @ workbench.desktop.main.js:sourcemap:5385
(anonymous) @ workbench.desktop.main.js:sourcemap:5382
_handle @ workbench.desktop.main.js:sourcemap:3683
acceptUsers @ workbench.desktop.main.js:sourcemap:3683
_handleExtensionPoint @ workbench.desktop.main.js:sourcemap:3918
_doHandleExtensionPoints @ workbench.desktop.main.js:sourcemap:3917
_registerAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4377
_startLocalExtensionHost @ workbench.desktop.main.js:sourcemap:4377
_scanAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4377
async function (async)
_scanAndHandleExtensions @ workbench.desktop.main.js:sourcemap:4374
_initialize @ workbench.desktop.main.js:sourcemap:3913
(anonymous) @ workbench.desktop.main.js:sourcemap:4369
requestIdleCallback (async)
t.runWhenIdle @ workbench.desktop.main.js:sourcemap:131
(anonymous) @ workbench.desktop.main.js:sourcemap:4369
Promise.then (async)
e @ workbench.desktop.main.js:sourcemap:4369
_createInstance @ workbench.desktop.main.js:sourcemap:1625
_createServiceInstance @ workbench.desktop.main.js:sourcemap:1627
_createServiceInstanceWithOwner @ workbench.desktop.main.js:sourcemap:1626
_createAndCacheServiceInstance @ workbench.desktop.main.js:sourcemap:1626
_getOrCreateServiceInstance @ workbench.desktop.main.js:sourcemap:1625
get @ workbench.desktop.main.js:sourcemap:1624
initLayout @ workbench.desktop.main.js:sourcemap:6178
(anonymous) @ workbench.desktop.main.js:sourcemap:6266
invokeFunction @ workbench.desktop.main.js:sourcemap:1624
startup @ workbench.desktop.main.js:sourcemap:6266
open @ workbench.desktop.main.js:sourcemap:7229
async function (async)
open @ workbench.desktop.main.js:sourcemap:7229
t.main @ workbench.desktop.main.js:sourcemap:7234
(anonymous) @ workbench.js:33
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ workbench.js:29
(anonymous) @ bootstrap-window.js:130
t._invokeFactory @ loader.js:1043
t.complete @ loader.js:1053
s._onModuleComplete @ loader.js:1674
s._onModuleComplete @ loader.js:1686
s._resolve @ loader.js:1634
s.defineModule @ loader.js:1281
r @ loader.js:1724
c @ loader.js:794
(anonymous) @ workbench.desktop.main.js:sourcemap:7255
(anonymous) @ workbench.desktop.main.js:sourcemap:7255
t._createAndEvalScript @ loader.js:797
(anonymous) @ loader.js:779
u @ loader.js:892
(anonymous) @ loader.js:897
readFileAfterClose @ internal/fs/read_file_context.js:61
workbench.desktop.main.js:sourcemap:259 [Extension Host] vscode-customcss is active!
workbench.desktop.main.js:sourcemap:259 [Extension Host] Congratulations, your extension "C compiler" is now active!
workbench.desktop.main.js:sourcemap:259 [Extension Host] ftp-simple start :  /Users/hackerwand/Library/Application Support/Code/User/globalStorage/humy2833.ftp-simple/ftp-simple.json
workbench.desktop.main.js:sourcemap:259 [Extension Host] WorkSpacePath : /Users/hackerwand/WebAPP/eloop
workbench.desktop.main.js:sourcemap:259 [Extension Host] vue
workbench.desktop.main.js:sourcemap:259 [Extension Host] Start child process...
workbench.desktop.main.js:sourcemap:259 [Extension Host] Error: ENOENT: no such file or directory, open '/Users/hackerwand/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/path.txt'	at Object.openSync (fs.js:447:3)	at Object.func (electron/js2c/asar.js:140:31)	at Object.func [as openSync] (electron/js2c/asar.js:140:31)	at Object.readFileSync (fs.js:349:35)	at Object.fs.readFileSync (electron/js2c/asar.js:542:40)	at Object.fs.readFileSync (electron/js2c/asar.js:542:40)	at Object.<anonymous> (/Users/hackerwand/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/index.js:4:42)	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)	at Module.load (internal/modules/cjs/loader.js:735:32)	at Module._load (internal/modules/cjs/loader.js:648:12)	at Module._load (electron/js2c/asar.js:717:26)	at Function.Module._load (electron/js2c/asar.js:717:26)	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:955:769)	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:106)	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:921:391)	at Module.require (internal/modules/cjs/loader.js:775:19)	at getHostCmd (/Users/hackerwand/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:316:41)	at /Users/hackerwand/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19	at Object.exports.sendRequest (/Users/hackerwand/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)	at pickConvert (/Users/hackerwand/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)	at exports.pick (/Users/hackerwand/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:627:894)	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:628:295)	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:757)	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:449)	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:787:120)	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:970)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:784:213	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:615)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:957:179	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:615)	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:17)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:234:155	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:230:129)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:229:483	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238:565)	at Socket.emit (events.js:203:13)	at addChunk (_stream_readable.js:295:12)	at readableAddChunk (_stream_readable.js:276:11)	at Socket.Readable.push (_stream_readable.js:210:10)	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
t.log @ workbench.desktop.main.js:sourcemap:259
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:4020
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:4026
_invokeHandler @ workbench.desktop.main.js:sourcemap:4026
_receiveRequest @ workbench.desktop.main.js:sourcemap:4025
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:4024
(anonymous) @ workbench.desktop.main.js:sourcemap:4022
fire @ workbench.desktop.main.js:sourcemap:95
fire @ workbench.desktop.main.js:sourcemap:424
_receiveMessage @ workbench.desktop.main.js:sourcemap:428
(anonymous) @ workbench.desktop.main.js:sourcemap:425
fire @ workbench.desktop.main.js:sourcemap:95
acceptChunk @ workbench.desktop.main.js:sourcemap:421
(anonymous) @ workbench.desktop.main.js:sourcemap:420
t @ workbench.desktop.main.js:sourcemap:431
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
workbench.desktop.main.js:sourcemap:2876 [processBridge]: Error: ENOENT: no such file or directory, open '/Users/hackerwand/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/path.txt'
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:2876
(anonymous) @ workbench.desktop.main.js:sourcemap:2876
fire @ workbench.desktop.main.js:sourcemap:95
addNotification @ workbench.desktop.main.js:sourcemap:2910
notify @ workbench.desktop.main.js:sourcemap:4263
(anonymous) @ workbench.desktop.main.js:sourcemap:3985
_showMessage @ workbench.desktop.main.js:sourcemap:3984
$showMessage @ workbench.desktop.main.js:sourcemap:3984
_doInvokeHandler @ workbench.desktop.main.js:sourcemap:4026
_invokeHandler @ workbench.desktop.main.js:sourcemap:4026
_receiveRequest @ workbench.desktop.main.js:sourcemap:4025
_receiveOneMessage @ workbench.desktop.main.js:sourcemap:4024
(anonymous) @ workbench.desktop.main.js:sourcemap:4022
fire @ workbench.desktop.main.js:sourcemap:95
fire @ workbench.desktop.main.js:sourcemap:424
_receiveMessage @ workbench.desktop.main.js:sourcemap:428
(anonymous) @ workbench.desktop.main.js:sourcemap:425
fire @ workbench.desktop.main.js:sourcemap:95
acceptChunk @ workbench.desktop.main.js:sourcemap:421
(anonymous) @ workbench.desktop.main.js:sourcemap:420
t @ workbench.desktop.main.js:sourcemap:431
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
workbench.desktop.main.js:sourcemap:259 [Extension Host] PHP Language Server: DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded

workbench.desktop.main.js:sourcemap:259 [Extension Host] PHP process connected
4workbench.desktop.main.js:sourcemap:259 [Extension Host] Untitled-1
```

**Comment by anseki** [comment]
Could you explain about the "Steps to Reproduce"?
For example, what does the "useless" mean?
Also, which command did you execute?

**Comment by HackerWand** [comment]
![image](https://user-images.githubusercontent.com/12233185/82402412-deaaf200-9a8e-11ea-9d65-4824aac45ce5.png)

No "Steps to Reproduce"，Normally, the mouse hover would activate the palette, but the palette was not activated under the vue file, and there were no color blocks in front of the color code. Then I tried to execute the Alt +c and Alt +c p commands and the error was reported as shown above

**Comment by anseki** [comment]
I see...
It seems that you mistook that.
That is internal Color Picker of VS Code, not the extension.
You have to ask to [VS Code team](https://github.com/Microsoft/vscode/issues), not here.

**Comment by HackerWand** [comment]
Ok and thank you

**Comment by anseki** [comment]
:smile:
